### PR TITLE
Add TIC-80 core

### PR DESCRIPTION
**Pull request by RobLoach**
Built and ran correctly on my Raspberry Pi, but would always love more testing!

### CODE REVIEW

**Comment by natinusala** [comment]
Is an update to core-info or libretro-database necessary?

**Comment by RobLoach** [comment]
YAAAAAAAAASSSSSSSSSSSSSSSSS

**Comment by ToKe79** [comment]
Hi,
the build of this PR (fb4b2521763e1d6735e089ea93d1d944160e23ab) finished successfully for all 44 targets.
Images for testing and logs are here: http://nightly.builds.lakka.tv/PRs/pr_699_fb4b252/

_This is an automated message_

**Comment by ToKe79** [comment]
Hi,
the build of this PR (a59979f3e0533ad8a08f95a9c5cd0469eb7289b2) finished successfully for all 44 targets.
Images for testing and logs are here: http://nightly.builds.lakka.tv/PRs/pr_699_a59979f/

_This is an automated message_

**Pull request merged**
