### PR TITLE
stella : Add stella to Libretro cores

### LINKED ISSUE #1133: Please add stella for the pie 4
If you could add stella to the pie 4 I would test it to see if it can run it at 60 fps or not.

### PR DESCRIPTION
**Pull request by gouchi**
- Fix #1133

### CODE REVIEW

**Comment by Ntemis** [comment]
It's not ready yet that's why i didn't enabled.
It fails on some target because of missing platform

**Comment by ToKe79** [comment]
Hi,
this PR (f8edd1e1618276309919524186a2d23b4b7e8812) did not build correctly for any target - all (20) builds failed.
Logs can be found here: http://nightly.builds.lakka.tv/PRs/pr_1137_000198/

_This is an automated message_

**Comment by RobLoach** [comment]
In addition, I think you have to align the cores with the playlists? I could be incorrect with that though.

**Comment by gouchi** [comment]
- Indeed it seems there is linking issue with libstdc++
-  I think it is [RA_PLAYLIST_NAMES](https://github.com/libretro/Lakka-LibreELEC/blob/master/distributions/Lakka/options#L275) and [RA_PLAYLIST_CORES](https://github.com/libretro/Lakka-LibreELEC/blob/master/distributions/Lakka/options#L351) which should be synced. ([Source](https://github.com/libretro/Lakka-LibreELEC/blob/master/packages/libretro/retroarch/package.mk#L234-L235))

**Comment by ToKe79** [comment]
Hi,
this PR (9fadd8de0555291feae6b0e3e8395f769ebe79fc) did not build correctly for any target - all (20) builds failed.
Logs can be found here: http://nightly.builds.lakka.tv/PRs/pr_1137_000218/

_This is an automated message_

**Pull request closed without merging**
