### PR TITLE
Adding initial support for ODROID-Go Super

### PR DESCRIPTION
**Pull request by h1aji**
Have ported patches for OGS from  https://github.com/EmuELEC/EmuELEC/commit/8e3f73cbb865b2ddcbfa91949092723d6a93405e

### CODE REVIEW

**Comment by Ntemis** [comment]
Do we absolutely need that retroarch update?

**Comment by h1aji** [comment]
@Ntemis thats not necessary

**Comment by Ntemis** [comment]
please revert retroarch to 1.9.0 stable

**Comment by h1aji** [comment]
done

**Pull request merged**
