### PR TITLE
Allwinner: Update kernel to v4.17.8

### PR DESCRIPTION
**Pull request by Thermionix**
mali nodes have been added to [allwinner device trees in 4.17](https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/diff/?id=da557d738466247f9437aaba2f2cd2afafa411ba) (fix for #307)

added packages to docker container to enable building u-boot (required for allwinner images)
`docker run -it -v $(pwd):/root -e DISTRO=Lakka -e PROJECT=Allwinner -e SYSTEM=Bananapi -e ARCH=arm lakka`
`docker run -it -v $(pwd):/root -e DISTRO=Lakka -e PROJECT=Allwinner -e SYSTEM=Linksprite_pcDuino3_Nano -e ARCH=arm lakka`

added Linksprite_pcDuino3_Nano target

### CODE REVIEW

**Comment by Ntemis** [comment]
Is A20 bootable for you?

**Comment by kivutar** [comment]
Builds are there http://static.kivutar.me/unstable/

**Comment by Ntemis** [comment]
H3 boots fine tested on orangepi pc but audio doesn't work. Overall PR looks promising as new kernel give a little boost to gaming performance but could be an after effect of no audio also :)

**Comment by kivutar** [comment]
It can definitely be an after effect of no audio. Sync to 60fps is done through audio, disabling audio most of the time runs the core as fast as possible.

**Comment by kivutar** [comment]
I just tried on Cubietruck (a20), the mali issue is still there.

**Comment by diizzyy** [comment]
I just tried it, boots but I'm still seeing random graphics corruption on my Orange Pi PC. It's vertical lines lines that flashes. Can anyone confirm?
It's very obvious during bootup but harder to see once Retroarch is running, still there though.

**Comment by Ntemis** [comment]
yeah no glitches here either @diizzyy

**Comment by kivutar** [comment]
I'm very suprised that this branch works without `projects/Allwinner/patches/linux/32-h3-DT-add-mali-node.patch`. Is this patch included in the new kernel?

**Comment by Thermionix** [comment]
Yes it is

On 30 July 2018 9:10:07 pm AEST, "Jean-André Santoni" <notifications@github.com> wrote:
>I'm very suprised that this branch works without
>`projects/Allwinner/patches/linux/32-h3-DT-add-mali-node.patch`. Is
>this patch included in the new kernel?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/libretro/Lakka-LibreELEC/pull/504#issuecomment-408828209

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by kivutar** [comment]
Can you check in the dtsi of sun7i-a20 if the mali node is also there please?

**Comment by Thermionix** [comment]
My pcduino3 is sun7i a20 with mali and yes mali node is there

On 30 July 2018 9:35:42 pm AEST, "Jean-André Santoni" <notifications@github.com> wrote:
>Can you check in the dtsi of sun7i-a20 if the mali node is also there
>please?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/libretro/Lakka-LibreELEC/pull/504#issuecomment-408833799

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by kivutar** [comment]
It's crazy, I'm not getting any mali nodes on my cubietruck...

**Comment by Ntemis** [comment]
Also i still don't get any audio

**Comment by Ntemis** [comment]
@Thermionix please update this PR and re-base it on master please or is going down the toilet.
Thanks

**Comment by Ioalevia** [comment]
banana pi a20. tried all latest versions of images. tried nightly versions. two varians: stucks with kernel fail or has ethernet fail. one year ago i used lakka on my device and it worked perfect. if anybody has lakka image for banana pi from 2016-2017????

**Comment by Ntemis** [comment]
@Ioalevia i will pass this one too as a lonely Sunday afternoon

**Pull request closed without merging**
