### PR TITLE
ODROID-Go Super: updated packages and patches

### PR DESCRIPTION
**Pull request by h1aji**

### CODE REVIEW

**Comment by davidgfnet** [comment]
Perhaps I did something wrong, but your patches did not bring up a usable system for me. The libmali is too old and RA won't come up. I sent https://github.com/libretro/Lakka-LibreELEC/pull/1196 instead, where we update the userspace driver and RA finally boots (or at least it does on my OGAs/OGS)

**Comment by davidgfnet** [comment]
Perhaps you can drop on Discord if you want and show me what you are saying about it being slow. I tested it with a few devices and it seems to work well for me, that's indeed odd.
Yeah perhaps your changes for the sleep mode can be dropped for now. If you want you could look into enabling sleep mode for all devices, since right now it's disabled sort of on purpose (not sure why).

**Comment by Ntemis** [comment]
@h1aji is this works https://github.com/libretro/Lakka-LibreELEC/pull/1195/commits/ffb8cd88aaf8762529bae2741ac186a90136d5a5 i would like to merge it so can you pr it alone please?

**Comment by h1aji** [comment]
> @h1aji is this works [ffb8cd8](https://github.com/libretro/Lakka-LibreELEC/commit/ffb8cd88aaf8762529bae2741ac186a90136d5a5) i would like to merge it so can you pr it alone please?

i was about to test it and build with latest commit but i am seeing this error 
```
/home/ubuntu/Lakka-LibreELEC/build.Lakka-OdroidGoAdvance.arm-3.0-devel/toolchain/bin/armv8a-libreelec-linux-gnueabi-gcc -march=armv8-a+crc -mtune=cortex-a35 -mabi=aapcs-linux -Wno-psabi -Wa,-mno-warn-deprecated -mfloat-abi=hard -mfpu=crypto-neon-fp-armv8 -fomit-frame-pointer -Wall -pipe -Os  -DGIT_VERSION=\"" 9af0702"\" -O2 -DNDEBUG -D__LIBRETRO__ -DHAVE_STRINGS_H -DHAVE_STDINT_H -DHAVE_INTTYPES_H  -DINLINE=inline -DHAS_GPU  -Wall -W -Wno-unused-parameter -Wno-sign-compare -Wno-uninitialized -fPIC -DFRONTEND_SUPPORTS_RGB565  -I. -I./libretro-common/include -I./libretro-common/include -c -olibretro-common/glsym/rglgen.o libretro-common/glsym/rglgen.c
/home/ubuntu/Lakka-LibreELEC/build.Lakka-OdroidGoAdvance.arm-3.0-devel/toolchain/bin/armv8a-libreelec-linux-gnueabi-gcc -march=armv8-a+crc -mtune=cortex-a35 -mabi=aapcs-linux -Wno-psabi -Wa,-mno-warn-deprecated -mfloat-abi=hard -mfpu=crypto-neon-fp-armv8 -fomit-frame-pointer -Wall -pipe -Os  -DGIT_VERSION=\"" 9af0702"\" -O2 -DNDEBUG -D__LIBRETRO__ -DHAVE_STRINGS_H -DHAVE_STDINT_H -DHAVE_INTTYPES_H  -DINLINE=inline -DHAS_GPU  -Wall -W -Wno-unused-parameter -Wno-sign-compare -Wno-uninitialized -fPIC -DFRONTEND_SUPPORTS_RGB565  -I. -I./libretro-common/include -I./libretro-common/include -c -olibretro-common/glsym/glsym_gl.o libretro-common/glsym/glsym_gl.c
In file included from ./libretro-common/include/glsym/rglgen_headers.h:31,
                 from ./libretro-common/include/glsym/rglgen.h:32,
                 from ./libretro-common/include/glsym/glsym.h:26,
                 from libretro-common/glsym/glsym_gl.c:25:
./libretro-common/include/glsym/rglgen_private_headers.h:67:10: fatal error: GL/gl.h: No such file or directory
   67 | #include <GL/gl.h>
      |          ^~~~~~~~~
compilation terminated.
make: *** [Makefile.libretro:745: libretro-common/glsym/glsym_gl.o] Error 1
make: *** Waiting for unfinished jobs....
In file included from ./libretro-common/include/glsym/rglgen_headers.h:31,
                 from ./libretro-common/include/glsym/rglgen.h:32,
                 from libretro-common/glsym/rglgen.c:26:
./libretro-common/include/glsym/rglgen_private_headers.h:67:10: fatal error: GL/gl.h: No such file or directory
   67 | #include <GL/gl.h>
      |          ^~~~~~~~~
compilation terminated.
make: *** [Makefile.libretro:745: libretro-common/glsym/rglgen.o] Error 1
In file included from ./libretro-common/include/glsym/rglgen_headers.h:31,
                 from ./libretro-common/include/glsym/rglgen.h:32,
                 from ./libretro-common/include/glsym/glsym.h:26,
                 from libretro.c:15:
./libretro-common/include/glsym/rglgen_private_headers.h:67:10: fatal error: GL/gl.h: No such file or directory
   67 | #include <GL/gl.h>
      |          ^~~~~~~~~
compilation terminated.
make: *** [Makefile.libretro:745: libretro.o] Error 1

```

when i am running
`PROJECT=Rockchip DEVICE=OdroidGoAdvance ARCH=arm make image`

**Comment by h1aji** [comment]
I was able to fix the error above with this workaround 
```
diff --git a/packages/libretro/vecx/package.mk b/packages/libretro/vecx/package.mk
index 0b542a82d2..58c059acfa 100644
--- a/packages/libretro/vecx/package.mk
+++ b/packages/libretro/vecx/package.mk
@@ -42,7 +42,7 @@ make_target() {
        make platform=rpi -f Makefile.libretro # broadcom gl/gles
     fi
  else
-    make -f Makefile.libretro
+    make platform=classic_armv8_a35 -f Makefile.libretro GLES=1 FORCE_GLES=1 HAVE_NEON=1
  fi
 }
 

```

**Comment by h1aji** [comment]
i think this patch is required: https://raw.githubusercontent.com/flatmax/buildroot.rk3308/master/patches.rockpis/uboot/0001-uboot-update.patch

**Comment by Ntemis** [comment]
Test and pr all your findings and help us make Lakka on OGA flawless.

**Comment by davidgfnet** [comment]
Have you tested this? I tried it but it seems that doesnt want to suspend?
systemd complains about hibernation stuff which... doesnt make a lot of sense

**Comment by h1aji** [comment]
@davidgfnet I am struggling to run build now. Fixed issue with vecx
```
diff --git a/packages/libretro/vecx/package.mk b/packages/libretro/vecx/package.mk
index 0b542a82d2..0d928bc2cc 100644
--- a/packages/libretro/vecx/package.mk
+++ b/packages/libretro/vecx/package.mk
@@ -35,12 +35,14 @@ PKG_IS_ADDON="no"
 PKG_AUTORECONF="no"
 
 make_target() {
-  if [ "$PROJECT" == "RPi" ]; then
+ if [ "$PROJECT" == "RPi" ]; then
     if [ "$DEVICE" == "RPi4" ]; then
        make platform=rpi-mesa -f Makefile.libretro # Use mesa gl/gles
     else
        make platform=rpi -f Makefile.libretro # broadcom gl/gles
     fi
+ elif [ "$DEVICE" == "OdroidGoAdvance" ]; then
+    make -f Makefile.libretro HAS_GPU=1 HAS_GLES=1
  else
     make -f Makefile.libretro
  fi

```

But now I am getting this right at the end
```
  LD      u-boot
  OBJCOPY u-boot.srec
  OBJCOPY u-boot-nodtb.bin
  SYM     u-boot.sym
  DTC     arch/arm/dts/rk3036-sdk.dtb
Error: arch/arm/dts/.rk3036-sdk.dtb.pre.tmp:77.1-10 syntax error
FATAL ERROR: Unable to parse input tree
make[3]: *** [scripts/Makefile.lib:319: arch/arm/dts/rk3036-sdk.dtb] Error 1
make[2]: *** [dts/Makefile:72: arch-dtbs] Error 2
make[1]: *** [Makefile:880: dts/dt.dtb] Error 2
make[1]: *** Waiting for unfinished jobs....
start=$(/home/ubuntu/Lakka-LibreELEC/build.Lakka-OdroidGoAdvance.arm-3.0-devel/toolchain/lib/gcc-arm-aarch64-linux-gnu/bin/aarch64-linux-gnu-nm u-boot | grep __rel_dyn_start | cut -f 1 -d ' '); end=$(/home/ubuntu/Lakka-LibreELEC/build.Lakka-OdroidGoAdvance.arm-3.0-devel/toolchain/lib/gcc-arm-aarch64-linux-gnu/bin/aarch64-linux-gnu-nm u-boot | grep __rel_dyn_end | cut -f 1 -d ' '); tools/relocate-rela u-boot-nodtb.bin 0x00200000 $start $end
make[1]: Leaving directory '/home/ubuntu/Lakka-LibreELEC/build.Lakka-OdroidGoAdvance.arm-3.0-devel/u-boot-a1b59905a4554055f35196e17301bf83cbe41b5f'
make: *** [Makefile:12: image] Error 2

```

**Comment by Ntemis** [comment]
why you closed this?

**Comment by h1aji** [comment]
@Ntemis I am unable to build it, so I cant test it properly. Will try later when the build process gets fixed

**Comment by Ntemis** [comment]
https://discord.gg/retroarch join #lakkatv

**Comment by kivutar** [comment]
I will have this device soon

**Pull request closed without merging**
