### PR TITLE
Bump version to 2.3.1

### PR DESCRIPTION
**Pull request by natinusala**

### CODE REVIEW

**Comment by natinusala** [comment]
Why would I not update OS_VERSION?

**Comment by ToKe79** [comment]
It was "2.2" also for 2.2.x releases and "2.1" for 2.1.x releases. So I thought it is bumped only when major there is a major version change.

**Comment by natinusala** [comment]
Oh okay then

Le ven. 20 sept. 2019 à 13:20, Tomáš Kelemen <notifications@github.com> a
écrit :

**Comment by ToKe79** [comment]
Hi,
the build of this PR (9d78bbbfe45f5adf0c9e8038ecef668dcb7fea9f) finished successfully for all 46 targets.
Images for testing and logs are here: http://nightly.builds.lakka.tv/PRs/pr_799_000091/

_This is an automated message_

**Pull request closed without merging**
