### PR TITLE
Bump libgpg-error to v1.37

### PR DESCRIPTION
**Pull request by davidgfnet**
This fixes issues with gawk v5.0.0, as described at:
https://dev.gnupg.org/T4459

### CODE REVIEW

**Comment by natinusala** [comment]
This causes failure on our build bot

http://nightly.builds.lakka.tv/2020-03-06/_logs/A64.arm-2020-03-06.txt

I don't see any error in that log though, what is happening?

**Comment by Ntemis** [comment]
Is the sha256 correct?

**Comment by natinusala** [comment]
It's a build error but it's not clearly stated in the logs, it looks like it builds fine and fails at the very last step

**Comment by Ntemis** [comment]
The binary has the same name?

**Comment by natinusala** [comment]
`***  Please report to <https://bugs.gnupg.org> with gpg-error-config-test.log`  there is clearly an error somewhere that the makefile detects

**Comment by ToKe79** [comment]
content of `gpg-error-config-test.log`:
```
Test result: --version
====================: ./gpg-error-config-old
1.37
====================: gpgrt-config
1.36
====================
Test result: --version
====================: ./gpg-error-config-old
1.37
====================: gpgrt-config
1.36
====================
```
`src/Makefile` about line 1747:
```
    1745 gpg-error-config: gpgrt-config gpg-error-config-old
    1746         @echo $(ECHO_N) "Confirm gpg-error-config works... $(ECHO_C)"
>>> 1747         @if ./gpg-error-config-test.sh --old-new; then \
    1748           echo "good";                                         \
    1749         else                                                   \
    1750           echo "no";                                           \
    1751           echo "***  Please report to <https://bugs.gnupg.org> with gpg-error-config-test.log"; \
    1752           exit 1; \
    1753         fi
    1754         cp gpg-error-config-old $@
```
`gpg-error-config-test.sh`:
```
    54 if [ "$PKG_CONFIG_CMD" = ./gpg-error-config-old ]; then
    55     OUTPUT_OLD=$(echo $($PKG_CONFIG_CMD --version))
    56     OUTPUT_NEW=$($srcdir/gpgrt-config --version)
>>> 57     [ "$OUTPUT_OLD" = "$OUTPUT_NEW" ] || failure --version
```

**Comment by natinusala** [comment]
> echo "good";
> echo "no";

Way to explain what's wrong...

I think the script has the wrong pkg-config prefix, where is `PKG_CONFIG_CMD` set? We could override that or simply remove that script call from the makefile

**Pull request merged**
