### PR TITLE
[WIP] [Do NOT Merge (yet)] RetroArch: add menu for Wi-Fi access point service

### PR DESCRIPTION
**Pull request by ToKe79**
This is only for test purposes, do not merge this in Lakka. Only using
the buildbot to build images of this patch, so it can be pushed
upstream, after it is tested.

### CODE REVIEW

**Comment by ToKe79** [comment]
Hi,
the build of this PR (1582617a6601838b0a9ac0c6b2a979c4dc7a80ec) finished successfully for all 46 targets.
Images for testing and logs are here: http://nightly.builds.lakka.tv/PRs/pr_792_000087/

_This is an automated message_

**Comment by ToKe79** [comment]
Hi,
the build of this PR (c2a71dad1a9714db00f9a1b09b0a774707682955) finished successfully for all 46 targets.
Images for testing and logs are here: http://nightly.builds.lakka.tv/PRs/pr_792_000094/

_This is an automated message_

**Comment by ToKe79** [comment]
Hi,
the build of this PR (349361a407dedb223b37239f2d10839f795ce607) finished successfully for all 46 targets.
Images for testing and logs are here: http://nightly.builds.lakka.tv/PRs/pr_792_000095/

_This is an automated message_

**Comment by ToKe79** [comment]
Hi,
the build of this PR (583d704ead582fe485530024b2493e9d158ad90f) finished successfully for all 46 targets.
Images for testing and logs are here: http://nightly.builds.lakka.tv/PRs/pr_792_000096/

_This is an automated message_

**Comment by ToKe79** [comment]
Hi,
the build of this PR (970b2856f0996649ce79c962c1e2a817b61ec750) finished successfully for all 46 targets.
Images for testing and logs are here: http://nightly.builds.lakka.tv/PRs/pr_792_000098/

_This is an automated message_

**Comment by ToKe79** [comment]
Hi,
the build of this PR (34cdaede1e3ae0cb40d82dd394176a2aeb9ba0e1) finished successfully for all 46 targets.
Images for testing and logs are here: http://nightly.builds.lakka.tv/PRs/pr_792_000099/

_This is an automated message_

**Comment by ToKe79** [comment]
Hi,
the build of this PR (7a4d5da5100f351596ac8369e371fb3665592c0b) finished successfully for all 46 targets.
Images for testing and logs are here: http://nightly.builds.lakka.tv/PRs/pr_792_000100/

_This is an automated message_

**Comment by ToKe79** [comment]
Hi,
the build of this PR (fb3d950d0e0ed8b1103531ddfa39629b8d457831) finished successfully for all 46 targets.
Images for testing and logs are here: http://nightly.builds.lakka.tv/PRs/pr_792_000102/

_This is an automated message_

**Comment by ToKe79** [comment]
Hi,
the build of this PR (91e0ca55b18752d8191678977b97eadd177b8e01) finished successfully for all 46 targets.
Images for testing and logs are here: http://nightly.builds.lakka.tv/PRs/pr_792_000105/

_This is an automated message_

**Comment by duduke** [comment]
IRL got into the way...
I've downloaded the latest build of this PR and did the following tests:

1. From scratch, turned ON Lakka AP and without connecting to any WIFI AP, I was able to connect and got a valid IPv4.
2. Without Reboot, turned OFF Lakka AP and successfully connected to my HOME AP for the first time.
3. Without Reboot, turned ON Lakka AP (while connected to HOME AP). Lakka successfully disconnected from my HOME AP and turned ON Lakka AP.
4. Did a Shutdown and Power on. Lakka connected to my HOME AP successfully.

I think this suggests that it is working correctly and can be merged.

Sorry for the delay.

**Comment by ToKe79** [comment]
merged upstream https://github.com/libretro/RetroArch/commit/92272fe01efd7bdd7e6ff85db5f8ac753148cad8

**Pull request closed without merging**
