### PR TITLE
get-git: new clone when remote changes

### PR DESCRIPTION
**Pull request by ToKe79**
removes original repo folder in case the remote has changed and makes a new clone of the new remote.
[dnb]

### CODE REVIEW

**Comment by natinusala** [comment]
This is really good, thanks for that

**Comment by ToKe79** [comment]
The original fix was not working properly + I added some output.

**Comment by ToKe79** [comment]
corrected the commit message

**Comment by natinusala** [comment]
Whoops, wrong account

Why doesn't GitHub allow login from multiple accounts like Google does

**Pull request merged**
