### PR TITLE
Update bluez to v5.48

### PR DESCRIPTION
**Pull request by Ntemis**

### CODE REVIEW

**Comment by kivutar** [comment]
Question: what does this update fixes?

Another question: will my DS3 controller **auto pair** when I plug it to the USB the first time (without having to type any command)?

**Comment by Ntemis** [comment]
Sure

Στις 1 Φεβ 2018 16:06, ο χρήστης "Jean-André Santoni" <
notifications@github.com> έγραψε:

**Comment by Ntemis** [comment]
Fixes all chinese unknown and known clones

Στις 1 Φεβ 2018 16:28, ο χρήστης ierokipides.dem@gmail.com έγραψε:

**Comment by gouchi** [comment]
Yes it  will provide some fixes for [PS3 clones joypads](http://www.hadess.net/2017/12/more-bluetooth-and-gaming-features.html) one is [hid](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/drivers/hid/hid-sony.c?id=492ca83c3d19fba1622164f07cd7b775596a7db2) the other one is [bluez](https://git.kernel.org/pub/scm/bluetooth/bluez.git/commit/plugins/sixaxis.c?id=1629c39ededef07988a5403b27331e0e317f1e08).

Thanks to @hadess

**Comment by hadess** [comment]
> Another question: will my DS3 controller auto pair when I plug it to the USB the first time (without having to type any command)?

As long as there is a "bluetoothd agent" running in the background and accepting the request. The first screenshot here is what it looks like in GNOME:
http://www.hadess.net/2017/09/bluetooth-on-fedora-joypads-and-more.html

**Comment by kivutar** [comment]
From IRC:

> [22:12:04] Substring i've tried it already
> [22:12:04] Substring have fun with sixaxis ...
> [22:12:36] Substring they added an authorization on sixaxis pairing to avoid some security issues
> [22:13:10] kivutar so auto pairing works or not?
> [22:13:26] Substring it doesn't
> [22:13:33] Substring as you have to authorize an uuid
> [22:13:48] Substring which means patch the sixpair plugin to get rid of the authorization
> [22:14:05] Substring and gasia still do not work
> [22:17:17] kivutar lol I was sure about it haha
> [22:17:42] Substring that's a hid-sony problem in fact

**Comment by hadess** [comment]
> [22:12:04] Substring i've tried it already
> [22:12:04] Substring have fun with sixaxis ...
> [22:12:36] Substring they added an authorization on sixaxis pairing to avoid some security issues
> [22:13:10] kivutar so auto pairing works or not?
> [22:13:26] Substring it doesn't
> [22:13:33] Substring as you have to authorize an uuid
> [22:13:48] Substring which means patch the sixpair plugin to get rid of the authorization

As mentioned in my comment and in the blog post.

> [22:14:05] Substring and gasia still do not work
> [22:17:17] kivutar lol I was sure about it haha
> [22:17:42] Substring that's a hid-sony problem in fact

That requires both a bluez patch (already in 5.48) for the device to be able to pair, and a kernel patch for the pad not to rumble when plugged in through USB. Both mentioned in:
http://www.hadess.net/2017/12/more-bluetooth-and-gaming-features.html

**Comment by kivutar** [comment]
I just tested it on RPi3 with my official (Not GASIA nor SHANWAN) DS3:

 - auto pairing not working
 - manual pairing not working

    Lakka:~ # bluetoothctl
    bluetoothctl: symbol lookup error: /usr/lib/libreadline.so.7: undefined symbol: UP

**Comment by substring** [comment]
@hadess Gasia are quite broken regarding the "standard sixaxis protocol". These chinese clones would work fine on USB, get the master address set fine with BlueZ, but they just do not connect with Bluetooth. The LEDs keep blinking, dmesg even shows a HID pad connected, but the driver misses something to "trigger" the pad into a working mode and te pad goes back to sleep. The good old qtsixa driver had some GAsia specific hacks, and according to my very small knowledge, the way LEDs were set slightly differed.

**Comment by Ntemis** [comment]
@kivutar we have the same issue with the current version also
Lakka:~ # bluetoothctl
bluetoothctl: error while loading shared libraries: libreadline.so.7: cannot open shared object file: No such file or directory

**Comment by kivutar** [comment]
@Ntemis I'm not getting this issue on the current version. I can auto pair my DS3 just fine.

**Pull request closed without merging**
