### PR TITLE
Rpi updates

### PR DESCRIPTION
**Pull request by dmrlawson**
Update kernel, firmware and drivers used by rpi (and others)

### CODE REVIEW

**Comment by gouchi** [comment]
Thank you for the PR.

I would have separated the update between the one related to RPi, mesa and vulkan.

**Comment by dmrlawson** [comment]
> Thank you for the PR.
> 
> I would have separated the update between the one related to RPi, mesa and vulkan.

Sure, I can do that if preferred?

**Comment by gouchi** [comment]
Just as mentioned in the [contributing doc](https://github.com/libretro/Lakka-LibreELEC/blob/master/CONTRIBUTING.md#pull-requests),

> Atomic, changes as less things as possible

@Ntemis @ToKe79 What do you think ?

**Comment by dmrlawson** [comment]
I must confess I hadn't read the contributing doc. I'll redo the commit messages to e.g. `mesa: update to 21.2.0` but it does feel a bit unnecessary to make separate PRs for simple updates.

If we want separate commits in the master branch to revert individual changes we could forgo the squashing.

**Comment by Ntemis** [comment]
Did you test the mesa update?

**Comment by dmrlawson** [comment]
Yes, I've tested with all these changes. I appreciate that these affect more than rpi so I will close this and make separate PRs. Sorry for the confusion :)

**Pull request closed without merging**
