### PR TITLE
Update glib to 2.54 to address compile errors

### PR DESCRIPTION
**Pull request by Zerauskire**
Update glib to address compile errors in newer versions of GCC.

### CODE REVIEW

**Comment by Kivutar** [comment]
We can keep this PR open for documentation purposes. But I can't merge it at this stage of the release process. Also I like to stick to LibreELEC when possible.

**Comment by Zerauskire** [comment]
Ok. No problem. LibreELEC is currently on 2.53.5 which would address this issue as well. So maybe just pull down from LibreELEC?

https://github.com/LibreELEC/LibreELEC.tv/blob/master/packages/devel/glib/package.mk

**Comment by Zerauskire** [comment]
Current version of LibreELEC also has an update to automake that addresses a regex issue i'm running into while compiling.

**Comment by Kivutar** [comment]
This branch is based on the stable LibreELEC 8.2
And the next version will be based on 8.4 or the next one.

**Pull request closed without merging**
