### PR TITLE
Update to LibreELEC 9.1.002

### PR DESCRIPTION
**Pull request by ToKe79**

### CODE REVIEW

**Comment by ToKe79** [comment]
This one should not be squashed, otherwise we lose the history and in next merge we will be merging these commits again (without any changes to the files).

**Comment by Ntemis** [comment]
Am all in for this to get in. Evry

**Comment by ToKe79** [comment]
yes, the images in latest folder are based on https://github.com/ToKe79/Lakka-LibreELEC/tree/lakka_le92-latest_9.1.002

**Comment by ToKe79** [comment]
and none of the commits of this pr affect Lakka directly. i just want to update to latest tag.

**Comment by natinusala** [comment]
Merged with standard merge method

**Pull request merged**
