### PR TITLE
core: add Super Bros War

### PR DESCRIPTION
**Pull request by loki666**
# Pull requests

### CODE REVIEW

**Comment by loki666** [comment]
please squash this mess :p

**Comment by loki666** [comment]
not compiling...

**Comment by loki666** [comment]
tested on RPi3, core worked fine, but seems like core info was missing

**Comment by ToKe79** [comment]
you have to bump the core-info package (`./libretro-update.sh -p core_info` iirc)

**Comment by loki666** [comment]
done

**Review by ToKe79 — APPROVED** [review]

**Pull request merged**
