### PR TITLE
libretro : add vircon32 libretro core

### PR DESCRIPTION
**Pull request by gouchi**
Core [info](https://github.com/libretro/libretro-core-info/blob/master/vircon32_libretro.info) and [database](https://github.com/libretro/libretro-database/blob/master/rdb/Vircon32.rdb) have been added in RA 1.6.0.

### CODE REVIEW

**Comment by gouchi** [comment]
Hi @Ntemis Anything prevent to merge it ? Should I update it ?

Thank you.

**Comment by Ntemis** [comment]
Looks like you have done nothing i asked in my review.

**Comment by gouchi** [comment]
@Ntemis which review ? And I don't see merge conflict.

**Comment by Ntemis** [comment]
> @Ntemis which review ? And I don't see merge conflict.

image

**Comment by Ntemis** [comment]
image

**Comment by Ntemis** [comment]
I think the above are obvious ones

**Comment by gouchi** [comment]
Will redo PR properly.

**Pull request closed without merging**
