### PR TITLE
Patches for glibc 2.28+ on Fedora

### PR DESCRIPTION
**Pull request by smokku**
These patches allow building Lakka on systems with glibc 2.28+
(ie. Fedora Linux)

Recent refactoring in glibc breaks assumptions built in gnulib and not updated yet software needs working around those assumptions.

### CODE REVIEW

**Comment by natinusala** [comment]
Thanks for the PR! Let's see if everything builds properly

**Comment by ToKe79** [comment]
Hi,
the build of this PR (821247a6770a15186a795b82d2b413cb5a8cff82) finished successfully for all 45 targets.
Images for testing and logs are here: http://nightly.builds.lakka.tv/PRs/pr_747_821247a/

_This is an automated message_

**Comment by slav0nic** [comment]
why not update bison version? AFAIK this patch already included in `bison>3.3.1`, `3.4.1` is latest

**Comment by smokku** [comment]
bison 3.4.1 indeed builds. If upgrade is a preferable solution, I will update the PR.

**Comment by natinusala** [comment]
I don't see any reason not to upgrade

**Comment by smokku** [comment]
It also required patches to include `sysmacros` from new glibc.

I also needed to manually `--disable-al` and `--disable-x11` in `retroarch` configure, as on my system it defaulted to supporting OpenAL and X11.

**Comment by smokku** [comment]
Phew... I also needed `--disable-cg` for the build to actually boot.

**Comment by smokku** [comment]
I also have one issue, that I do not know proper way to approach.

The build breaks on:
```
which: no mkimage in (/home/smoku/devel/Arcade/Lakka-LibreELEC/build.Lakka-Generic.x86_64-2.2-devel/toolchain/bin:/home/smoku/devel/Arcade/Lakka-LibreELEC/build.Lakka-Generic.x86_64-2.2-devel/toolchain/sbin:...
```
It looks like x86_64 build is looking for `mkimage` which is a part of u-boot, which should not be needed on x86 platform.

I temporarly patched it like so:
```diff
--- a/scripts/image
+++ b/scripts/image
@@ -306,7 +306,7 @@ if [ "$1" = "release" -o "$1" = "mkimage" -o "$1" = "amlpkg" -o "$1" = "noobs" ]
     INSTALL_SRC_DIR="$PROJECT_DIR/$PROJECT/install"
   fi
 
-  MKIMAGE_TOOL_CMD="$(which mkimage) -A $TARGET_KERNEL_ARCH -O linux -T script -C none -d"
+  MKIMAGE_TOOL_CMD="$(which mkimage || :) -A $TARGET_KERNEL_ARCH -O linux -T script -C none -d"
 
   # cleanup
   rm -rf $RELEASE_DIR
```
but this is not a real solution, is it?

**Comment by natinusala** [comment]
Add uboot tools as a host dependency for the breaking package. We may already have it, I'm not sure if we do. Lakka Switch may also have it as well.

**Comment by ToKe79** [comment]
Hi,
the build of this PR (209e3813291f237690bbb1f5d38776ee795f9138) finished successfully for all 45 targets.
Images for testing and logs are here: http://nightly.builds.lakka.tv/PRs/pr_747_209e381/

_This is an automated message_

**Comment by ToKe79** [comment]
Hi,
the build of this PR (e3696ab0ccd9a12685258188efa42d4ae88be58b) finished successfully for all 45 targets.
Images for testing and logs are here: http://nightly.builds.lakka.tv/PRs/pr_747_e3696ab/

_This is an automated message_

**Comment by natinusala** [comment]
That's a big diff but nothing is critical (mostly build / system tools) - why the change to qemu? Do we ever use it?

**Comment by smokku** [comment]
qemu 2.7.0 build fails due to sysmacros.h changes:
```
/usr/bin/ld: qga/commands-posix.o: in function `dev_major_minor':
/home/smoku/devel/Arcade/Lakka-LibreELEC/build.Lakka-Generic.x86_64-2.2-devel/qemu-2.7.0/qga/commands-posix.c:656: undefined reference to `major'
/usr/bin/ld: /home/smoku/devel/Arcade/Lakka-LibreELEC/build.Lakka-Generic.x86_64-2.2-devel/qemu-2.7.0/qga/commands-posix.c:657: undefined reference to `minor'
collect2: error: ld returned 1 exit status
```

**Comment by natinusala** [comment]
But what is qemu used for? Host tools?

**Comment by smokku** [comment]
```
  INSTALL    udevil (target)
  INSTALL    fuse-exfat (target)
      INSTALL    fuse (target)
  INSTALL    ntfs-3g_ntfsprogs (target)
  INSTALL    virtual (target)
      CLEAN    qemu
          * Removing /home/smoku/devel/Arcade/Lakka-LibreELEC/build.Lakka-Generic.x86_64-2.2-devel/qemu-2.10.2 ...
      UNPACK   qemu
          APPLY PATCH (common)   packages/tools/qemu/patches/qemu-01-memfd-fix-configure-test.patch
```

**Comment by natinusala** [comment]
It's used for the virtualbox image (that doesn't work) it seems

**Comment by Ntemis** [comment]
is this PR still needed?

**Comment by smokku** [comment]
Just checked and current (`db102f6e80`) lakka/master still fails build under Fedora.

```
> lsb_release -d
Description:	Fedora release 31 (Thirty One)
```

**Pull request merged**
