### PR TITLE
libretro-cores: new package, add master switch

### PR DESCRIPTION
**Pull request by natinusala**
I added a new `libretro-cores` packages to avoid reusing `$LIBRETRO_CORES` in every platform metapackage.

I also added a new build option, `DISABLE_LIBRETRO=yes` that temporarly removes all cores from the system, useful to speed up compilation when porting Lakka to new platforms.

### CODE REVIEW

**Comment by ToKe79** [comment]
Hi,
this PR (300dd5beb83a57dce572c59e52fa6ae645ac921a) did not build correctly for all targets.
Following targets failed (4):
- Generic.x86_64
- GPICase.arm
- RPi.arm
- Dragonboard.arm

Logs and images for testing can be found here: http://nightly.builds.lakka.tv/PRs/pr_898_000141/

_This is an automated message_

**Comment by natinusala** [comment]
Yeah it's sameboy throwing a tantrum, consider the PR working lol

**Comment by ToKe79** [comment]
Hi,
this PR (00d688fa67074608843b1ab5f6795b709729abc3) did not build correctly for all targets.
Following targets failed (4):
- Generic.x86_64
- GPICase.arm
- RPi.arm
- Dragonboard.arm

Logs and images for testing can be found here: http://nightly.builds.lakka.tv/PRs/pr_898_000142/

_This is an automated message_

**Comment by ToKe79** [comment]
Looks OK to me, however we can get rid of some of the meta-packages, at least for now (Odroid*, Generic_VK, Virtual, WandBoard, ...). We currently do not have any project files for these and some are obsolete.

And I think there is no requirement for a approving review to merge?

**Comment by natinusala** [comment]
> And I think there is no requirement for a approving review to merge?

What do you mean?

**Comment by ToKe79** [comment]
@natinusala I cannot see that this PR was approved, but it was possible to to merge the PR. maybe when you were force-pushing the LE92 branch to master, you switched off the protection - in repository settings -> branch, there should be some options to protect a branch, e.g. require PR reviews before merging.

**Comment by natinusala** [comment]
Good catch, I disabled it to force push and I totally forgot to re-enable it

**Pull request merged**
