### PR TITLE
Fix Lakka-v6.x build failure on Odin & Switch linux

### PR DESCRIPTION
**Pull request by ShigeakiAsai**
### Lakka-v6.x nightly build failure was happened in the following 3 devices from 13th June 2024.
- Odin
- Raspberry Pi 3
- Switch
In this pull request, fixe Odin and Switch both build failure. 

<BR>

### Reason
The Odin and Switch are caused by a patch apply fail for linux.
Both are same reason, the base file is old, more 1 patch is needs.
For this commit. 
https://github.com/libretro/Lakka-LibreELEC/commit/4330a07750d1e4bc4ebb3e6b293ae7dd22ae5645
\+ This patch (commit) is also needed for both devices.
https://github.com/torvalds/linux/commit/c30411266fd67ea3c02a05c157231654d5a3bdc9

<BR>

### Remove : 1 file , Add 6 files
- packages/linux/patches/linux-999.99-backport-media-anysee-accept-read-buffers-of-length-1.patch
  Remove this file from common directory, and copy it to each project patch directory.

- packages/linux/patches/default/linux-999.99-backport-media-anysee-accept-read-buffers-of-length-1.patch
  Add(Copy from common directory).

- packages/linux/patches/raspberrypi/linux-999.99-backport-media-anysee-accept-read-buffers-of-length-1.patch
  Add(Copy from common directory).

- projects/Ayn/devices/Odin/patches/linux/linux-999.98-backport-media-anysee-fix-null-ptr-deref-in-anysee_master_xfe.patch
  Add more 1 patch file.
- projects/Ayn/devices/Odin/patches/linux/linux-999.99-backport-media-anysee-accept-read-buffers-of-length-1.patch
  Add(Copy from common directory).

- projects/L4T/patches/linux/linux-999.98-backport-media-anysee-fix-null-ptr-deref-in-anysee_master_xfe.patch
  Add more 1 patch file.
- projects/L4T/patches/linux/linux-999.99-backport-media-anysee-accept-read-buffers-of-length-1.patch
  Add(Copy from common directory).

<BR>

### Confirmatrion
I confirmed build is passed and patch is applied in the following devices.
- Odin.aarch64(Ayn)
- Switch.aarch64(L4T)
- RPi4-GPiCase2.aarch64(RPi)
- AMLGX.aarch64(Amlogic)
- RK3328.aarch64(Rockchip)

<BR>

Thanks
ASAI, Shigeaki

### CODE REVIEW

**Review by Ntemis — APPROVED** [review]

**Comment by ShigeakiAsai** [comment]
It is included in 26th June 2024 nightly build.

Thanks.
ASAI, Shigeaki

**Comment by readybrek** [comment]
Apologies first of all if this is the wrong place to put this. I've had a build failure having cloned the repository (yesterday, 17th Nov 2024) into a fresh Ubuntu 24.04 VM. I tried the build recipe from https://docs.libretro.com/guides/building-lakka/ for a first gen raspberry pi (i.e. "DISTRO=Lakka PROJECT=RPi DEVICE=RPi ARCH=arm make image         # for the Raspberry Pi"). It made it as far as the 'linux' package and seemed to trip up on applying the same patch twice to '~/Lakka-LibreELEC/build.Lakka-RPi.arm/build/linux-66aef6ce3557edd9d58d794e4a800c5be49ca0e7/drivers/media/usb/dvb-usb-v2/anysee.c'. I tracked back through the raspberry pi patches folder and found two identical files with different file names;

1. ~/Lakka-LibreELEC/packages/linux/patches/raspberrypi/linux-999.90-media-anysee-accept-read-buffers-of-length-1-in-anys.patch
2. ~/Lakka-LibreELEC/packages/linux/patches/raspberrypi/linux-999.99-backport-media-anysee-accept-read-buffers-of-length-1.patch

This seems to have caused 'patch' to recognise the prior application of the file '1' and prevent further processing. See log excerpt below:

`    [1;32mAPPLY PATCH [1;37m(common - raspberrypi)[0m[0m      packages/linux/patches/raspberrypi/linux-999.90-media-anysee-accept-read-buffers-of-length-1-in-anys.patch
patching file drivers/media/usb/dvb-usb-v2/anysee.c
    [1;32mAPPLY PATCH [1;37m(common - raspberrypi)[0m[0m      packages/linux/patches/raspberrypi/linux-999.99-backport-media-anysee-accept-read-buffers-of-length-1.patch
patching file drivers/media/usb/dvb-usb-v2/anysee.c
Reversed (or previously applied) patch detected!  Assume -R? [n] 
Apply anyway? [n] 
Skipping patch.
1 out of 1 hunk ignored -- saving rejects to file drivers/media/usb/dvb-usb-v2/anysee.c.rej
*********** FAILED COMMAND ***********
patch -d "${PKG_BUILD}" -p1 < ${i} >&${VERBOSE_OUT}
**************************************
*********** FAILED COMMAND ***********
${SCRIPTS}/unpack "${PKG_NAME}" "${PARENT_PKG}"
**************************************
[1;31mFAILURE: scripts/build linux:host has failed![0m`

I resolved by removing the first file and (successfully) rebuilding the package.

Hope this helped someone!

**Comment by ShigeakiAsai** [comment]
@readybrek

Thank you for your notifying.
As you said, the cause of RPi build fail is there are same patch file with different filename.
I will fix it via new PR creation.

Thanks
ASAI, Shigeaki

**Comment by GavinDarkglider** [comment]
As the developer of the switch, and Odin ports, I am curious what the relevance of these patches are, or why we need them for lakka specifically? There is no core that uses dvb devices in lakka. This is clearly a patch to fix issues with Kodi, and might not be needed, and probably aren't needed in lakka, let alone in 4.9 kernel used on the switch.

**Comment by ShigeakiAsai** [comment]
Hello @GavinDarkglider

This PR purpose was only to fix the build break by the upstream merging.

Upstream linux patch file was contained common directory.
So, I also made to put them(and more) into switch/odin/RPi3.
I didn't care it nesessary or not.

If switch/odin are not need them, please remove them.

Thanks
ASAI, Shigeaki

**Pull request merged**
