### PR TITLE
desmume: fix/update url

### PR DESCRIPTION
**Pull request by ToKe79**
core was moved (?)

### CODE REVIEW

**Comment by gouchi** [comment]
Yes it seems there are [three repositories](https://github.com/libretro?utf8=%E2%9C%93&q=desmume&type=&language=) now.

**Comment by kivutar** [comment]
So, are you sure it is the same source code as before @ToKe79 ?

**Comment by ToKe79** [comment]
On the /desmume repo it is not possible to checkout the commit defined in our PKG_VERSION. With this url it is possible.
But with the commits from https://github.com/libretro/desmume2015/commit/69658a23a8fb02c533f1f60c23311c925243d722 the target is `desmume2015_libretro.so`. We have to keep this in mind if we update this core later (update `makeinstall_target()`), or I could also update it to last version now and update it too in this PR (but I have no games to test with).

**Comment by RobLoach** [comment]
Suggest sticking with the unyear'ed one:
https://github.com/libretro/desmume

**Comment by ToKe79** [comment]
@RobLoach but that one is the different one. For a short time the /desmume url was opening/redirecting to /desmume2015

**Comment by Ntemis** [comment]
Imo better follow upstream and ditch 2015

**Comment by ToKe79** [comment]
Just FYI - the new desmume core requires OpenGL, which we do not have for all boards, so we could include it, but only for specific targets/projects/devices.

**Comment by RobLoach** [comment]
s/permanent/temporary

**Comment by Ntemis** [comment]
Fixed, thanks

**Pull request merged**
