### PR TITLE
yabasanshiro: new core

### PR DESCRIPTION
**Pull request by plaidman**
compiles and runs on switch. has a problem where the games freeze every few minutes. haven't yet diagnosed.

### CODE REVIEW

**Comment by plaidman** [comment]
@natinusala I marked this core as aarch64 only because it hasn't really been tested on other platforms has it? Should we include others? Should we even include this at all for aarch64 since it doesn't really work 100% on switch anyway? When it does run it's full speed but we have the freezing issue that we haven't solved yet.

**Comment by natinusala** [comment]
I would say to add it to all archs, but it will depends on how well it runs / if it runs at all

**Comment by plaidman** [comment]
updated for all archs.

**Comment by natinusala** [comment]
Can you do the same for kronos please?

**Comment by plaidman** [comment]
kronos is already 'any'

**Comment by natinusala** [comment]
I am building images for Generic, RPi2 and ROCKPro64 to test yaba sanshiro and kronos - I will need someone to test Generic for me, and all other platforms if needed (or we can assume that it works on all boards if it works on RPi and ROCKPro64)

**Pull request merged**
