### PR TITLE
Update reicast, fix compilation for ARM

### PR DESCRIPTION
**Pull request by kivutar**
This needs to be tested
i386 build broken

### CODE REVIEW

**Comment by twinaphex** [comment]
Reicast should work on 32bit x86 now.

**Comment by kivutar** [comment]
Good to know. I'm getting this kind of errors when compiling for i386:

```core/hw/arm7/arm7.cpp: In function 'void arm_compilecode()':
core/hw/arm7/arm7.cpp:1467:2: error: expected '(' before '{' token
  {
  ^
core/hw/arm7/arm7.cpp:1468:3: error: 'call' was not declared in this scope
   call CompileCode;
   ^~~~
core/hw/arm7/arm7.cpp:1468:3: note: suggested alternative: 'calloc'
   call CompileCode;
   ^~~~
   calloc
core/hw/arm7/arm7.cpp:1469:3: error: 'mov' was not declared in this scope
   mov eax,0;
   ^~~
core/hw/arm7/arm7.cpp:1470:3: error: 'jmp' was not declared in this scope
   jmp arm_dispatch;
   ^~~
core/hw/arm7/arm7.cpp:1470:3: note: suggested alternative: 'bcmp'
   jmp arm_dispatch;
   ^~~
   bcmp```

**Comment by twinaphex** [comment]
Pushed commit which might help -

https://github.com/libretro/reicast-emulator/commit/056afcc3ea3a87488f3e9be74177fedae3c99ed4

**Comment by kivutar** [comment]
Perfect, you fixed it!

**Comment by gouchi** [comment]
- Builds ok for i386 and Tinkerboard arm.
- Working ok for i386.
- Tinkerboard arm I tested DC Power Stone 2 (OK but slow), Ikaruga (color issue, slow), Rez (OK but slow). If needed I can provide screenshot.

**Pull request merged**
