### PR TITLE
Retroarch: Update all Libretro cores

### PR DESCRIPTION
**Pull request by Ntemis**

### CODE REVIEW

**Comment by Ntemis** [comment]
Divide and conquer per wises

**Comment by kivutar** [comment]
OK, this PR contains a RetroArch upgrade as well as many other sensitive package upgrades. We need to be careful about regressions.

@Ntemis @gouchi @ToKe79 Can one of you build this, run it on real hardware and proceed to a few tests like running test roms?

I won't be able to test this by myself before a few days for family reasons

**Comment by ToKe79** [comment]
Started the build of all projects/platforms, the images will be stored here:
http://nightly.builds.lakka.tv/special_builds/pr_395/

**Comment by Ntemis** [comment]
Dont merge this as Retroarch 1.7.1 is out

**Pull request closed without merging**
