### PR TITLE
Lakka 9.2

### PR DESCRIPTION
**Pull request by Ntemis**

### CODE REVIEW

**Comment by ToKe79** [comment]
Hi,
this PR (3d42b3a84c11bd03c119ebd9b6de8934c91e181c) did not build correctly for any target - all (16) builds failed.
Logs can be found here: http://nightly.builds.lakka.tv/PRs/pr_965_000147/

_This is an automated message_

**Comment by Ntemis** [comment]
@ToKe79 why i am seeing this error? ERROR: No distro version present

**Comment by natinusala** [comment]
@Ntemis it looks like they added a version file in the distribution folder: https://github.com/LibreELEC/LibreELEC.tv/blob/master/distributions/LibreELEC/version

Can you add it for Lakka in your PR?

**Comment by Ntemis** [comment]
Absolutely afh atm but asap am back

Στις Παρ, 12 Ιουν 2020, 18:18 ο χρήστης Nathan S. <notifications@github.com>
έγραψε:

**Comment by Ntemis** [comment]
@natinusala done

**Comment by ToKe79** [comment]
Hi,
this PR (af753b157570ab6efe251838b01fc401d57d71b6) did not build correctly for any target - all (16) builds failed.
Logs can be found here: http://nightly.builds.lakka.tv/PRs/pr_965_000148/

_This is an automated message_

**Comment by natinusala** [comment]
It looks like they changed how OEM packages work too, look at the failure logs

**Comment by Ntemis** [comment]
it has to do in what build command is used on our side is PROJECT= defined at all?

**Comment by natinusala** [comment]
Yeah it is, `PROJECT=RPi`

Did they change the RPi project again?

**Comment by Ntemis** [comment]
I will build something to test but am sure we are not using the correct arguments

**Comment by Ntemis** [comment]
@natinusala works fine on my part
this command started me a build just fine
DISTRO=Lakka PROJECT=Rockchip DEVICE=TinkerBoard ARCH=arm make

**Comment by natinusala** [comment]
Can you try RPi4?

**Comment by Ntemis** [comment]
Fine as well this works:
DISTRO=Lakka PROJECT=RPi DEVICE=RPi4 ARCH=arm make

**Comment by Ntemis** [comment]
ow wait 
Configuration for LibreELEC (community) wtf?

**Comment by Ntemis** [comment]
Ok fixed and pushed

**Comment by Ntemis** [comment]
GTG

**Comment by ToKe79** [comment]
Hi,
this PR (0484198aab7dfd1688b6bfe0fe5b9e3f20bbcffe) did not build correctly for any target - all (16) builds failed.
Logs can be found here: http://nightly.builds.lakka.tv/PRs/pr_965_000149/

_This is an automated message_

**Comment by Ntemis** [comment]
it tried to build for x86/64 so ARCH=arm is no-op somehow

**Comment by Ntemis** [comment]
hum parallel-20190722 -> it build le cores.
Do we have oem folder enabled for our distro?

**Comment by natinusala** [comment]
It should be enabled yes

**Comment by ToKe79** [comment]
Hi,
this PR (2efa87019e005fba2cbf89f4c422bb467ec433e3) did not build correctly for any target - all (16) builds failed.
Logs can be found here: http://nightly.builds.lakka.tv/PRs/pr_965_000150/

_This is an automated message_

**Comment by ToKe79** [comment]
Hi,
this PR (961e759bc3c14c8822374a54331d865c17c619f8) did not build correctly for all targets.
Following targets failed (15):
- A64.arm
- H3.arm
- H6.arm
- AMLG12.arm
- AMLGX.arm
- Generic.x86_64
- Generic.i386
- MiQi.arm
- RK3328.arm
- RK3399.arm
- TinkerBoard.arm
- RPi.arm
- RPi2.arm
- RPi4.arm
- Dragonboard.arm

Logs and images for testing can be found here: http://nightly.builds.lakka.tv/PRs/pr_965_000151/

_This is an automated message_

**Comment by natinusala** [comment]
@Ntemis does your local build work for, say, rpi? or do you also have that libgpg error?

**Comment by Ntemis** [comment]
that issue was there before this pr

**Comment by ToKe79** [comment]
Hi,
this PR (a1223ceab53031e9fe0e3a90b533d5f27b37c22b) did not build correctly for any target - all (16) builds failed.
Logs can be found here: http://nightly.builds.lakka.tv/PRs/pr_965_000152/

_This is an automated message_

**Comment by Ntemis** [comment]
@ToKe79 Please make clean as i compile tested this and builds fine

**Pull request merged**
