### PR TITLE
libretro-database: update to the latest database

### PR DESCRIPTION
**Pull request by RobLoach**

### CODE REVIEW

**Comment by Ntemis** [comment]
Since 1.7.1 is out i see no reason for individual core updates.

**Comment by RobLoach** [comment]
You mean, do all libretro-related packages in one PR?

**Comment by Ntemis** [comment]
If you indent to do 1by1 you would need a week and then 1.7.2 might get out(e.g as a bug fix)

**Comment by RobLoach** [comment]
I intended to update libretro-database, since there are a change we need.

I'm okay with doing them all at once though.

**Comment by Ntemis** [comment]
In my opinion would be better for all of us and we can **all** test at once

**Comment by Ntemis** [comment]
Wondering if you need to re-open this one @RobLoach

**Pull request merged**
