### PR TITLE
Add Dragonboard-410C support to lakka

### PR DESCRIPTION
**Pull request by Ntemis**
https://developer.qualcomm.com/hardware/dragonboard-410c

Signed-off-by: Ntemis <ierokipides.dem@gmail.com>

### CODE REVIEW

**Comment by natinusala** [comment]
Looks clean to me, let's see if it breaks any existing project but there's no reason to

**Comment by Ntemis** [comment]
Clean build fails alas :) don't merge yet

**Comment by Ntemis** [comment]
now is GTG

**Comment by ToKe79** [comment]
I am fixing Allwinner project linux patches. I will send separate PR either to https://github.com/Ntemis/Lakka-LibreELEC/tree/Lakka-LE9.2 or here as a new PR.

Also, @Ntemis if you do not want the RTL8192CU RTL8192DU RTL8192EU RTL8188EU RTL8812AU drivers to be built, do not comment it out, but remove them from ADDITIONAL_DRIVERS, i.e.:

     ADDITIONAL_DRIVERS=""

By default they are included via distro-options:
https://github.com/libretro/Lakka-LibreELEC/blob/abb7f0c77e13a12a98379a31de848e860d327fc6/distributions/Lakka/options#L32-L36

**Comment by Ntemis** [comment]
Same out come. Commenting them out or deleting the line. I just left is there for troubleshooting purposes.

**Comment by ToKe79** [comment]
it is not the same, distro sets them, you have to override the distro setting by putting empty value.

**Comment by ToKe79** [comment]
anyway, they are building fine

**Comment by Ntemis** [comment]
I just realized what you meant and am sorry. 
Thing is i don't see the usefulness of these out of tree drivers on a mainline kernel.
If you want me to change it per project fine with me.

**Pull request merged**
