### PR TITLE
Rpi4 aarch64

### PR DESCRIPTION
**Pull request by dmrlawson**
I made this. I don't think it breaks the normal build so maybe it could be included if people want to build it themselves (simply changing `ARCH=arm` to `ARCH=aarch64`).

I have a patch for mupen64plus-next which I'll submit to that project and then update this.

There might not be much appetite for 64-bit at the moment but it _does_ allow us to play with dolphin and duckstation.

I've had duckstation running with the WIP vulkan driver and it works really well!

### CODE REVIEW

**Comment by Ntemis** [comment]
you have typos and you disabled cores vs patching them.
This pr cant be compiled as it is

**Comment by dmrlawson** [comment]
I'm pretty sure it compiles for aarch64, I need to test arm still.

Which typos are you talking about?

**Comment by Ntemis** [comment]
yes typo is fixed now, thanks.

**Comment by dmrlawson** [comment]
> you disabled cores vs patching them

Yes. I marked this as WIP and intend to go through and fix them, I mainly wanted to share and get feedback on my progress at this point.

From what I can tell there _are_ no official aarch64 builds though so though they're disabled (by making them not build for aarch64) does this have any impact?

Some of the failures are due to assumptions that RPi builds are 32-bit and so manually specify using NEON, which causes an error in aarch64 (where it's implicitly available).

**Comment by dmrlawson** [comment]
What would you like to see to get this merged?

If I disable non-building packages _only_ for rpi4-aarch64 would that be sufficient?

**Comment by SpaceAgeHero** [comment]
Wow, does Duckstation work including PGXP? Would love to see a video demonstration.

**Comment by dmrlawson** [comment]
> Wow, does Duckstation work including PGXP? Would love to see a video demonstration.

Doesn't seem to be working at the moment. I had it running on Raspberry Pi OS but it seems to struggle with the video driver on this. I'll see if I can figure it out.

**Comment by dmrlawson** [comment]
I've removed packages that don't currently build _only_ from this build.

**Comment by Ntemis** [comment]
Much better, weldone

**Review by Ntemis — DISMISSED** [review]

**Comment by dmrlawson** [comment]
Sound isn't working, possibly due to the new kernel.

I'm trying to figure out the proper way to generate the kernel config using https://www.raspberrypi.org/documentation/linux/kernel/building.md

**Pull request merged**
