### PR TITLE
A series of package updates to stable versions finetuned and tested

### PR DESCRIPTION
**Pull request by Ntemis**

### CODE REVIEW

**Comment by Ntemis** [comment]
They also fixed samba compile on my side

**Comment by ToKe79** [comment]
Hi,
this PR (731ea7036a79260d891e1834569567387ab74eda) did not build correctly for all targets.
Following targets failed (19):
- Generic.x86_64
- RPi.arm
- imx6.cuboxi.arm
- imx6.udoo.arm
- OdroidC1.arm
- WeTek_Core.arm
- WeTek_Play.arm
- S8X2.S82.arm
- S8X2.M8.arm
- S8X2.T8.arm
- S8X2.MXIII-1G.arm
- S8X2.MXIII-PLUS.arm
- S8X2.X8H-PLUS.arm
- S805.MXQ.arm
- S805.HD18Q.arm
- S805.M201C.arm
- S805.M201D.arm
- S805.MK808B-Plus.arm
- Slice.arm

Logs and images for testing can be found here: http://nightly.builds.lakka.tv/PRs/pr_696_731ea70/

_This is an automated message_

**Comment by Ntemis** [comment]
I clean build it my self on X86_64 with Bionic OS

**Comment by natinusala** [comment]
Seeing that GCC changed, I would advise to clean all platforms before testing

**Comment by natinusala** [comment]
And seeing the errors on the RPi project, I think cleaning them will make them build

**Comment by ToKe79** [comment]
restarted with clean build folders. give it some days...

**Comment by ToKe79** [comment]
Hi,
this PR (731ea7036a79260d891e1834569567387ab74eda) did not build correctly for any target - all (46) builds failed.
Logs can be found here: http://nightly.builds.lakka.tv/PRs/pr_696_731ea70/

_This is an automated message_

**Comment by natinusala** [comment]
It's the same commit id as before, we can ignore it right?

**Comment by ToKe79** [comment]
Hi,
this PR (fd1d9fbc846b13826ef37b54c3c802ee7ef8b246) did not build correctly for any target - all (46) builds failed.
Logs can be found here: http://nightly.builds.lakka.tv/PRs/pr_696_fd1d9fb/

_This is an automated message_

**Comment by natinusala** [comment]
Looks like libblkid needs updating

**Comment by Ntemis** [comment]
@ToKe79 try again

**Comment by SumavisionQ5** [comment]
parallel n64 core is not correctly built for S905, all N64 games will have graphic glitches. If you try N64 games with parallel N64 built for Playstation Classic, the graphic glitches will be gone. 
@Ntemis Can you try to fix it?

**Comment by Ntemis** [comment]
@SumavisionQ5 there is no comparison between the two and there is nothing to do.
When we migrate to mainline kernel and mesa drivers sometime after summer S905 should be more capable vs the current state, but have in mind that that soc is considered weak from my tests on it.
Its good as a media player but sucks hard as a gaming platform

**Comment by shantigilbert** [comment]
> but have in mind that that soc is considered weak from my tests on it.
> Its good as a media player but sucks hard as a gaming platform

Sorry to go off-topic but this is interesting to me, as I have been using the S905 for emulation for a few years now and found it equal or even better than the RPI3, granted it does run on an old kernel and needs a few hacks here and there, but the soc is more than capable of good emulation.

Could you elaborate on your tests?

**Comment by Ntemis** [comment]
You are comparing oranges to apples. Ofc is better than an RPI3 but that doesn't make it a capable soc for gaming. For my benchmarking anything that cant run Zelda ocarina of time at 720p is a waist of time. Everything now day's can run 2d cores like nes snes megadrive etc but when the real gaming begins most socs  fail flat.

**Comment by shantigilbert** [comment]
> You are comparing oranges to apples. Ofc is better than an RPI3 but that doesn't make it a capable soc for gaming. For my benchmarking anything that cant run Zelda ocarina of time at 720p is a waist of time. Everything now day's can run 2d cores like nes snes megadrive etc but when the real gaming begins most socs fail flat.

Considering the RPI3 is a VERY popular emulation machine, that is similar to the S905 not sure how I am comparing oranges to apples, but fair enough, I agree you won't get PC-like performance on a $20 dll box, but it still doesn't "sucks hard as a gaming platform" unless you have unreal expectations. Anyways I was just curious about your comment, thanks for answering.

**Comment by natinusala** [comment]
@ToKe79 do we need to fire the bot again for this PR?

**Comment by Ntemis** [comment]
i probably need to split up the packages for better testing and reliability

**Comment by natinusala** [comment]
That's a good idea, the smaller the PRs are the better it is

**Comment by Ntemis** [comment]
no time on this one so am closing down R.I.P

**Pull request closed without merging**
