### PR TITLE
new libretro core mupen64plus-libretro-nx

### PR DESCRIPTION
**Pull request by ToKe79**
+ package name: mupen64plus_next
+ disabled for targets:
  RPi / Slice / Gamegirl / OdroidXU3 - does not build

### CODE REVIEW

**Comment by natinusala** [comment]
It should work on Raspberry Pi, why doesn't it?

Also, mupen64plus can be removed on targets with mupen64plus-next working. I suppose parallel-n64 can be replaced by ParaLLExt too.

**Comment by natinusala** [comment]
Also, is the core-info package up to date?

**Comment by ToKe79** [comment]
For RPi, Gamegirl and Slice the compilation ends with:
```
mupen64plus-core/src/device/r4300/new_dynarec/arm/linkage_arm.S: Assembler messages:
mupen64plus-core/src/device/r4300/new_dynarec/arm/linkage_arm.S:177: Error: selected processor does not support `movw r3,#:lower16:fp_restore_candidate' in ARM mode
mupen64plus-core/src/device/r4300/new_dynarec/arm/linkage_arm.S:178: Error: selected processor does not support `movt r3,#:upper16:fp_restore_candidate' in ARM mode
make: *** [Makefile:442: mupen64plus-core/src/device/r4300/new_dynarec/arm/linkage_arm.o] Error 1
````
OdroidXU3 compilation ends with:
```
In file included from GLideN64/src/Graphics/OpenGLContext/GLFunctions.h:19:0,
                 from GLideN64/src/Graphics/OpenGLContext/GLFunctions.cpp:6:
./GLideN64/src/inc/GL/glcorearb.h:2258:149: error: conflicting declaration 'typedef void (* GLDEBUGPROC)(GLenum, GLenum, GLuint, GLenum, GLsizei, const GLchar*, const void*)'
 typedef void (APIENTRY  *GLDEBUGPROC)(GLenum source,GLenum type,GLuint id,GLenum severity,GLsizei length,const GLchar *message,const void *userParam);
                                                                                                                                                     ^
In file included from ./libretro-common/include/glsym/rglgen_headers.h:62:0,
                 from ./libretro-common/include/glsm/glsm.h:30,
                 from ./libretro-common/include/glsm/glsmsym.h:26,
                 from GLideN64/src/Graphics/OpenGLContext/GLFunctions.cpp:2:
/home/vudiq/projects/Lakka-LibreELEC/build.Lakka-OdroidXU3.arm/toolchain/armv7ve-libreelec-linux-gnueabi/sysroot/usr/include/GLES2/gl2ext.h:186:28: note: previous declaration as 'typedef void (* GLDEBUGPROC)(GLenum, GLenum, GLuint, GLenum, GLsizei, const GLchar*, GLvoid*)'
 typedef void (GL_APIENTRYP GLDEBUGPROC)(GLenum source,GLenum type,GLuint id,GLenum severity,GLsizei length,const GLchar *message,GLvoid *userParam);
                            ^~~~~~~~~~~
make: *** [Makefile:448: GLideN64/src/Graphics/OpenGLContext/GLFunctions.o] Error 1
```

I think it makes nothing worse if the original mupen64plus is kept (at least as fallback?).

And thank you for the reminder - core-info updated.

**Comment by natinusala** [comment]
Well, you should at least have mupen64plus-next as default for the playlist in the distro options. This core supersedes the old one :P

Let me ask m4xw if he know about that build issue for RPi

**Comment by natinusala** [comment]
Well, the core doesn't support RPi1, only RPi2 and 3

**Comment by ToKe79** [comment]
Thanks, I will revise the default core lists and commit.

**Comment by ToKe79** [comment]
rebased and resolved conflict

**Comment by natinusala** [comment]
How about core association / playlists?

**Comment by ToKe79** [comment]
That is already for devices (except RPi/Gamegirl/Slice/OdroidXU3) where mupen64plus was the default core for Nintendo 64 (https://github.com/libretro/Lakka-LibreELEC/pull/650/commits/f0b3796d6d51fd894d534237054ec63152bf0fc0), but I left the DISTRO  options unchanged (parallel_n64). Or did I miss something? Would you prefer have it as default core everywhere?

**Comment by natinusala** [comment]
Oh right, that's fine as it is. We'll make it default for all platforms with Lakka 3.0 (we'll probably drop support for all platforms not supporting -next anyway)

**Pull request merged**
