### PR TITLE
race: add new libretro core

### LINKED ISSUE #1638: Add lr-race to GPI + Zero 1 Build
Currently the GPI case + zero 1 3.7 build only includes one core for neogeo pocket: beetle neopop. It doesn't run well on the weak zero 1 hardware. I've heard good words about the race core running at 60 fps on zero 1. Can we add the race core to the build?

### PR DESCRIPTION
**Pull request by ToKe79**
closes: #1638

### CODE REVIEW

**Comment by Ntemis** [comment]
Can you amend commit and add the closes argument , thank you.

**Comment by smilerliu** [comment]
There is a thread about lr-race in RetroPie: https://retropie.org.uk/forum/topic/26824/lr-race-for-neo-geo-pocket-neo-geo-pocket-color

It seems someone made it work and DRZ80=1 needs to be set when compiling the core to have good speed. I have no idea whether the Lakka build system sets it or not; just a note.

**Comment by smilerliu** [comment]
I opened the issue #1638 and I'll be happy to test a PR build.

**Comment by ToKe79** [comment]
@smilerliu thanks, the PR build is already in progress, so the change with `DRZ80=1` will be built later. to speed things up you can test core from [here](https://nightly.builds.lakka.tv/members/vudiq/race_libretro.so) - just copy it via samba to `Cores`, or scp to `/tmp/cores` or copy it to the second partition into folder `cores`.

**Comment by smilerliu** [comment]
Tested the core in the link. It worked really well. For Metal Slug 1, I got 60 FPS or close to it all the time for the few mins of testing.

**Pull request merged**
