### PR TITLE
Lakka 3.0

### PR DESCRIPTION
**Pull request by Ntemis**
This PR brings Lakka on par with the upstream LE9.2 repo

### CODE REVIEW

**Comment by natinusala** [comment]
Thanks for the PR!

I suppose this must not be squashed

**Comment by Ntemis** [comment]
yeap, keeping track whats changed upstream and more readable this way

**Comment by ToKe79** [comment]
Hi,
this PR (8fe811009e2555a87dd952cd928012522f32149e) did not build correctly for all targets.
Following targets failed (2):
- Gamegirl.arm
- RPi4.arm

Logs and images for testing can be found here: http://nightly.builds.lakka.tv/PRs/pr_858_000119/

_This is an automated message_

**Comment by ToKe79** [comment]
Hi,
this PR (010ee6d324b774257f45aef9ab2bb12db65a4928) did not build correctly for all targets.
Following targets failed (2):
- Gamegirl.arm
- RPi4.arm

Logs and images for testing can be found here: http://nightly.builds.lakka.tv/PRs/pr_858_000120/

_This is an automated message_

**Comment by ToKe79** [comment]
Hi,
this PR (010ee6d324b774257f45aef9ab2bb12db65a4928) did not build correctly for all targets.
Following targets failed (2):
- Gamegirl.arm
- RPi4.arm

Logs and images for testing can be found here: http://nightly.builds.lakka.tv/PRs/pr_858_000121/

_This is an automated message_

**Comment by autofire372** [comment]
As far as I can tell, this breaks direct tty access on the Asus Tinker Board. Adding "tty retroarch=0" to extlinux.conf just leads to an effective softlock, as no command line comes up when CTRL+ALT+F3 is pressed.

**Comment by ToKe79** [comment]
@Ntemis can you remove these two lines?
```patch
diff --git a/packages/graphics/bcm2835-driver/package.mk b/packages/graphics/bcm2835-driver/package.mk
index 03859c6f10..5483bebbae 100644
--- a/packages/graphics/bcm2835-driver/package.mk
+++ b/packages/graphics/bcm2835-driver/package.mk
@@ -23,9 +23,7 @@ post_unpack() {
   # do not build GLES stuff when not using as GLES driver
   if [ "${OPENGLES}" != "bcm2835-driver" -a "${OPENGL}" != "bcm2835-driver" ]; then
     rm -v $PKG_BUILD/$PKG_FLOAT/opt/vc/lib/pkgconfig/brcmegl.pc
-    rm -v $PKG_BUILD/$PKG_FLOAT/opt/vc/lib/pkgconfig/egl.pc
     rm -v $PKG_BUILD/$PKG_FLOAT/opt/vc/lib/pkgconfig/brcmglesv2.pc
-    rm -v $PKG_BUILD/$PKG_FLOAT/opt/vc/lib/pkgconfig/glesv2.pc

     rm -v $PKG_BUILD/$PKG_FLOAT/opt/vc/lib/libbrcmEGL.so
     rm -v $PKG_BUILD/$PKG_FLOAT/opt/vc/lib/libbrcmGLESv2.so
```

**Comment by natinusala** [comment]
Well I would like to know what happened to EGL before having it removed like that

Did we touch the `bcm2835-driver` package on the LE9 branch? Why does it fail for us?

**Comment by Ntemis** [comment]
https://github.com/libretro/Lakka-LibreELEC/pull/858/commits/6e05ca4a690933fa26e638ecd450c5ddadbfb0de

**Comment by natinusala** [comment]
Do we want to update the bootrom / bootloader from Lakka? Not sure

**Comment by Ntemis** [comment]
that's for the usb-3.0 (via) chip

**Comment by Ntemis** [comment]
What is more weird is that i don't see that commit in the LE9.2 branch at all 
https://github.com/LibreELEC/LibreELEC.tv/commits/libreelec-9.2/packages/graphics/bcm2835-driver

**Comment by ToKe79** [comment]
@Ntemis nope, the version of the package was bumped couple of times, but this is the last commit/change:
https://github.com/libretro/Lakka-LibreELEC/pull/858/commits/09b0403f0ecd77ae38e4a647d557d6246ef001cc

@natinusala probably only Broadcom knows why those files were removed.

Simply said, the RPi4 build ("mesa" != "bcm2835-driver") fails because it cannot remove files that do not exist. I wonder if RPi/RPi2 have now EGL/GLES.But binary files and headers are still there, only files for pkgconfig are missing (not sure if those are needed to build GL-cores). But removing those two lines from package.mk fixes the build failure.

**Comment by Ntemis** [comment]
@natinusala  am all ears on how we resolve this

**Comment by natinusala** [comment]
The .pc files are important, however brcmglesv2 is used instead of glesv2, and I'm not sure if we're using EGL so we need to try on hardware to be sure

**Comment by ToKe79** [comment]
for egl there still is brcmegl.pc. I merged this and #860 into new branch (https://github.com/ToKe79/Lakka-LibreELEC/tree/pr858%2Bpr860) and started separate build. I will post the images when done.

**Comment by ToKe79** [comment]
I linked http://nightly.builds.lakka.tv/Lakka-LE9.2/oven/ to my target folder, so the images will appear here as soon as they are built.

**Comment by ToKe79** [comment]
Hi,
this PR (20d099b25b8f5155911449e66f342197397b0a69) did not build correctly for any target - all (16) builds failed.
Logs can be found here: http://nightly.builds.lakka.tv/PRs/pr_858_000124/

_This is an automated message_

**Comment by natinusala** [comment]
Can you maybe remove your merge commits? And then I'll try RPi4 from the oven and merge it

Next step will be removing Gamegirl from the projects entirely

**Comment by Ntemis** [comment]
i see no reason to clean up my merge commits tbh.
So go ahead if you gonna merge this as we need to do a mesa bump to 19.3.1 and an xu4 port

**Comment by ToKe79** [comment]
The merge commits (from LE to Lakka) are OK, IMHO.

So was anybody able to test the RPi builds from [here](http://nightly.builds.lakka.tv/Lakka-LE9.2/oven/)? I do not have the HW, so I cannot test these. Those builds also include the change - removed two lines in package.mk of the `bcm2835-driver` package.

@natinusala the `rm -v ...` lines were added by me - we do the same also in master:
https://github.com/libretro/Lakka-LibreELEC/blob/b5b3c1292a2367c1e7b41d74620e9347b3c1ea2d/packages/graphics/bcm2835-driver/package.mk#L25-L29

but the current version of this package does not have two of the four .pc files, so it fails.

@Ntemis please remove these two lines

https://github.com/Ntemis/Lakka-LibreELEC/blob/20d099b25b8f5155911449e66f342197397b0a69/packages/graphics/bcm2835-driver/package.mk#L26

https://github.com/Ntemis/Lakka-LibreELEC/blob/20d099b25b8f5155911449e66f342197397b0a69/packages/graphics/bcm2835-driver/package.mk#L28

and commit/push the change to your branch, so it shows up here as well. thanks!

**Comment by natinusala** [comment]
I will try it after the new master release

**Comment by ToKe79** [comment]
Anyway - I think any consequent build of this PR will fail due to some RetroArch cores/packages. But a rebase (upstream/Lakka-LE92) + forced push should solve it.

**Comment by Ntemis** [comment]
@natinusala @ToKe79 Now it should be gtg.
Merged also again from upstream. Cause: samba updated

**Comment by ToKe79** [comment]
Hi,
this PR (0c3cf59559e4c4c1ce24f5e5ecb7c3b4d0d8681c) did not build correctly for any target - all (16) builds failed.
Logs can be found here: http://nightly.builds.lakka.tv/PRs/pr_858_000128/

_This is an automated message_

**Comment by ToKe79** [comment]
Hi,
this PR (d30b00a9223f88714e476efc0bc721a93031cb11) did not build correctly for any target - all (16) builds failed.
Logs can be found here: http://nightly.builds.lakka.tv/PRs/pr_858_000129/

_This is an automated message_

**Comment by Ntemis** [comment]
So whats the issue here? Am i expected to fix all cores so this can be merged?
Since i don't touch any , merge it then we go from there.

**Comment by ToKe79** [comment]
@Ntemis no need to fix the cores. but you deleted the whole post_unpack() function, only deletion of two lines was needed.
However I think we should merge the 9.2.0 tag and nothing after. We do not need the "bleeding edge".

**Comment by Ntemis** [comment]
If you read my message in the commit is clear.
Le9.2 is not cutting edge as is on maintenance mode only. Master is the current cutting edge

**Comment by ToKe79** [comment]
that's why the quotes around bleeding edge :)

can you revert https://github.com/libretro/Lakka-LibreELEC/pull/858/commits/d30b00a9223f88714e476efc0bc721a93031cb11 and only delete these lines from post_unpack():
```
    rm -v $PKG_BUILD/$PKG_FLOAT/opt/vc/lib/pkgconfig/egl.pc	
```
and
```
    rm -v $PKG_BUILD/$PKG_FLOAT/opt/vc/lib/pkgconfig/glesv2.pc	
```
I think we can merge then.

**Comment by natinusala** [comment]
Just a note to myself, after merging this :
- remove Gamegirl
- backport the libretro-cores package from #838
- have retroarch and libretro-cores be built from the distribution directly instead of as dependency of each project metapackage (RA is inherent to Lakka + having RA and the cores in every metapackage is impractical)
- yet another libretro update

**Pull request merged**
