### PR TITLE
openlara: enable for all targets

### PR DESCRIPTION
**Pull request by ToKe79**
added patches for arm:
- fix build when GL_TEXTURE_3D is not in the GLES headers provided by
the OPENGLES package
- fix build when extra CXXFLAGS are needed

### CODE REVIEW

**Comment by ToKe79** [comment]
Hi,
the build of this PR (93bd9cc73cb4ff5a5457da6c3a02e61b53922e9e) finished successfully for all 44 targets.
Images for testing and logs are here: http://nightly.builds.lakka.tv/PRs/pr_701_93bd9cc/

_This is an automated message_

**Comment by natinusala** [comment]
Nice, does the core work on GLES with the changes?

**Comment by ToKe79** [comment]
could not test by myself, I don't have any device to test with :-/

**Comment by natinusala** [comment]
I'll try it on RK3399 then

**Comment by ToKe79** [comment]
I fixed the patch for GL_TEXTURE_3D (was not working correctly for arm target using OpenGL (on LE9.2 branch)

**Comment by ToKe79** [comment]
Hi,
the build of this PR (2f31c4bbc66e7c79e58766272740684877d4bb6d) finished successfully for all 44 targets.
Images for testing and logs are here: http://nightly.builds.lakka.tv/PRs/pr_701_2f31c4b/

_This is an automated message_

**Comment by natinusala** [comment]
I think GL_TEXTURE_3D_OES is an OpenGL ES extension, is it available on all platforms?

**Comment by ToKe79** [comment]
I am no programmer, so I will answer how I came up with the patch.

I searched for `GL_TEXTURE_3D` in the `$SYSROOT_PREFIX/usr/include` folders and noticed that some OpenGLES platforms have only `GL_TEXTURE_3D_OES`, some have both - `GL_TEXTURE_3D` & `GL_TEXTURE_3D_OES`. In case they have both, they have the same value, so I think it does not make any difference if `GL_TEXTURE_3D` or `GL_TEXTURE_3D_OES` is used, right? In all cases the value is always the same - `0x80F6`.

Here is the output:
```
$ grep "^#define GL_TEXTURE_3D.*" build.Lakka-*/toolchain/*/sysroot/usr/include/*GL* -r | grep -v _KHR | grep -v _EXT
build.Lakka-Allwinner.arm/toolchain/armv7ve-libreelec-linux-gnueabi/sysroot/usr/include/GLES2/gl2ext.h:#define GL_TEXTURE_3D_OES                                       0x806F
build.Lakka-Gamegirl.arm/toolchain/armv6zk-libreelec-linux-gnueabi/sysroot/usr/include/GLES2/gl2ext.h:#define GL_TEXTURE_3D_OES                                       0x806F
build.Lakka-Generic.i386/toolchain/i686-libreelec-linux-gnu/sysroot/usr/include/GL/gl.h:#define GL_TEXTURE_3D				0x806F
build.Lakka-Generic.i386/toolchain/i686-libreelec-linux-gnu/sysroot/usr/include/GL/glext.h:#define GL_TEXTURE_3D                     0x806F
build.Lakka-Generic.i386/toolchain/i686-libreelec-linux-gnu/sysroot/usr/include/GL/glcorearb.h:#define GL_TEXTURE_3D                     0x806F
build.Lakka-Generic_VK_nvidia.x86_64/toolchain/x86_64-libreelec-linux-gnu/sysroot/usr/include/GL/gl.h:#define GL_TEXTURE_3D				0x806F
build.Lakka-Generic_VK_nvidia.x86_64/toolchain/x86_64-libreelec-linux-gnu/sysroot/usr/include/GL/glext.h:#define GL_TEXTURE_3D                     0x806F
build.Lakka-Generic_VK_nvidia.x86_64/toolchain/x86_64-libreelec-linux-gnu/sysroot/usr/include/GL/glcorearb.h:#define GL_TEXTURE_3D                     0x806F
build.Lakka-Generic.x86_64/toolchain/x86_64-libreelec-linux-gnu/sysroot/usr/include/GL/gl.h:#define GL_TEXTURE_3D				0x806F
build.Lakka-Generic.x86_64/toolchain/x86_64-libreelec-linux-gnu/sysroot/usr/include/GL/glext.h:#define GL_TEXTURE_3D                     0x806F
build.Lakka-Generic.x86_64/toolchain/x86_64-libreelec-linux-gnu/sysroot/usr/include/GL/glcorearb.h:#define GL_TEXTURE_3D                     0x806F
build.Lakka-imx6.arm/toolchain/armv7a-libreelec-linux-gnueabi/sysroot/usr/include/GL/gl.h:#define GL_TEXTURE_3D				0x806F
build.Lakka-imx6.arm/toolchain/armv7a-libreelec-linux-gnueabi/sysroot/usr/include/GL/glext.h:#define GL_TEXTURE_3D                     0x806F
build.Lakka-imx6.arm/toolchain/armv7a-libreelec-linux-gnueabi/sysroot/usr/include/GLES2/gl2ext.h:#define GL_TEXTURE_3D_OES                 0x806F
build.Lakka-imx6.arm/toolchain/armv7a-libreelec-linux-gnueabi/sysroot/usr/include/GLES3/gl3.h:#define GL_TEXTURE_3D                     0x806F
build.Lakka-MiQi.arm/toolchain/armv7ve-libreelec-linux-gnueabi/sysroot/usr/include/GLES2/gl2ext.h:#define GL_TEXTURE_3D_OES                 0x806F
build.Lakka-MiQi.arm/toolchain/armv7ve-libreelec-linux-gnueabi/sysroot/usr/include/GLES2/gl2ext.h:#define GL_TEXTURE_3D                     0x806F
build.Lakka-MiQi.arm/toolchain/armv7ve-libreelec-linux-gnueabi/sysroot/usr/include/GLES3/gl31.h:#define GL_TEXTURE_3D                     0x806F
build.Lakka-MiQi.arm/toolchain/armv7ve-libreelec-linux-gnueabi/sysroot/usr/include/GLES3/gl32.h:#define GL_TEXTURE_3D                     0x806F
build.Lakka-MiQi.arm/toolchain/armv7ve-libreelec-linux-gnueabi/sysroot/usr/include/GLES3/gl3.h:#define GL_TEXTURE_3D                     0x806F
build.Lakka-OdroidC1.arm/toolchain/armv7a-libreelec-linux-gnueabi/sysroot/usr/include/GLES2/gl2ext.h:#define GL_TEXTURE_3D_OES                                       0x806F
build.Lakka-Odroid_C2.arm/toolchain/armv8a-libreelec-linux-gnueabi/sysroot/usr/include/GLES2/gl2ext.h:#define GL_TEXTURE_3D_OES                                       0x806F
build.Lakka-OdroidXU3.arm/toolchain/armv7ve-libreelec-linux-gnueabi/sysroot/usr/include/GL/gl.h:#define GL_TEXTURE_3D				0x806F
build.Lakka-OdroidXU3.arm/toolchain/armv7ve-libreelec-linux-gnueabi/sysroot/usr/include/GL/glext.h:#define GL_TEXTURE_3D                     0x806F
build.Lakka-OdroidXU3.arm/toolchain/armv7ve-libreelec-linux-gnueabi/sysroot/usr/include/GL/glcorearb.h:#define GL_TEXTURE_3D                     0x806F
build.Lakka-OdroidXU3.arm/toolchain/armv7ve-libreelec-linux-gnueabi/sysroot/usr/include/GLES2/gl2ext.h:#define GL_TEXTURE_3D_OES                                       0x806F
build.Lakka-OdroidXU3.arm/toolchain/armv7ve-libreelec-linux-gnueabi/sysroot/usr/include/GLES3/gl31.h:#define GL_TEXTURE_3D                     0x806F
build.Lakka-OdroidXU3.arm/toolchain/armv7ve-libreelec-linux-gnueabi/sysroot/usr/include/GLES3/gl32.h:#define GL_TEXTURE_3D                     0x806F
build.Lakka-OdroidXU3.arm/toolchain/armv7ve-libreelec-linux-gnueabi/sysroot/usr/include/GLES3/gl3.h:#define GL_TEXTURE_3D                                    0x806F
build.Lakka-ROCK64.arm/toolchain/armv8a-libreelec-linux-gnueabi/sysroot/usr/include/GLES2/gl2ext.h:#define GL_TEXTURE_3D_OES                 0x806F
build.Lakka-ROCK64.arm/toolchain/armv8a-libreelec-linux-gnueabi/sysroot/usr/include/GLES2/gl2ext.h:#define GL_TEXTURE_3D                     0x806F
build.Lakka-ROCK64.arm/toolchain/armv8a-libreelec-linux-gnueabi/sysroot/usr/include/GLES3/gl31.h:#define GL_TEXTURE_3D                     0x806F
build.Lakka-ROCK64.arm/toolchain/armv8a-libreelec-linux-gnueabi/sysroot/usr/include/GLES3/gl32.h:#define GL_TEXTURE_3D                     0x806F
build.Lakka-ROCK64.arm/toolchain/armv8a-libreelec-linux-gnueabi/sysroot/usr/include/GLES3/gl3.h:#define GL_TEXTURE_3D                     0x806F
build.Lakka-ROCK960.arm/toolchain/armv8a-libreelec-linux-gnueabi/sysroot/usr/include/GLES2/gl2ext.h:#define GL_TEXTURE_3D_OES                 0x806F
build.Lakka-ROCK960.arm/toolchain/armv8a-libreelec-linux-gnueabi/sysroot/usr/include/GLES2/gl2ext.h:#define GL_TEXTURE_3D                     0x806F
build.Lakka-ROCK960.arm/toolchain/armv8a-libreelec-linux-gnueabi/sysroot/usr/include/GLES3/gl31.h:#define GL_TEXTURE_3D                     0x806F
build.Lakka-ROCK960.arm/toolchain/armv8a-libreelec-linux-gnueabi/sysroot/usr/include/GLES3/gl32.h:#define GL_TEXTURE_3D                     0x806F
build.Lakka-ROCK960.arm/toolchain/armv8a-libreelec-linux-gnueabi/sysroot/usr/include/GLES3/gl3.h:#define GL_TEXTURE_3D                     0x806F
build.Lakka-ROCKPro64.arm/toolchain/armv8a-libreelec-linux-gnueabi/sysroot/usr/include/GLES2/gl2ext.h:#define GL_TEXTURE_3D_OES                 0x806F
build.Lakka-ROCKPro64.arm/toolchain/armv8a-libreelec-linux-gnueabi/sysroot/usr/include/GLES2/gl2ext.h:#define GL_TEXTURE_3D                     0x806F
build.Lakka-ROCKPro64.arm/toolchain/armv8a-libreelec-linux-gnueabi/sysroot/usr/include/GLES3/gl31.h:#define GL_TEXTURE_3D                     0x806F
build.Lakka-ROCKPro64.arm/toolchain/armv8a-libreelec-linux-gnueabi/sysroot/usr/include/GLES3/gl32.h:#define GL_TEXTURE_3D                     0x806F
build.Lakka-ROCKPro64.arm/toolchain/armv8a-libreelec-linux-gnueabi/sysroot/usr/include/GLES3/gl3.h:#define GL_TEXTURE_3D                     0x806F
build.Lakka-ROC-RK3328-CC.arm/toolchain/armv8a-libreelec-linux-gnueabi/sysroot/usr/include/GLES2/gl2ext.h:#define GL_TEXTURE_3D_OES                 0x806F
build.Lakka-ROC-RK3328-CC.arm/toolchain/armv8a-libreelec-linux-gnueabi/sysroot/usr/include/GLES2/gl2ext.h:#define GL_TEXTURE_3D                     0x806F
build.Lakka-ROC-RK3328-CC.arm/toolchain/armv8a-libreelec-linux-gnueabi/sysroot/usr/include/GLES3/gl31.h:#define GL_TEXTURE_3D                     0x806F
build.Lakka-ROC-RK3328-CC.arm/toolchain/armv8a-libreelec-linux-gnueabi/sysroot/usr/include/GLES3/gl32.h:#define GL_TEXTURE_3D                     0x806F
build.Lakka-ROC-RK3328-CC.arm/toolchain/armv8a-libreelec-linux-gnueabi/sysroot/usr/include/GLES3/gl3.h:#define GL_TEXTURE_3D                     0x806F
build.Lakka-RPi2.arm/toolchain/armv7ve-libreelec-linux-gnueabi/sysroot/usr/include/GLES2/gl2ext.h:#define GL_TEXTURE_3D_OES                                       0x806F
build.Lakka-RPi4.arm/toolchain/armv8a-libreelec-linux-gnueabi/sysroot/usr/include/GL/gl.h:#define GL_TEXTURE_3D				0x806F
build.Lakka-RPi4.arm/toolchain/armv8a-libreelec-linux-gnueabi/sysroot/usr/include/GL/glext.h:#define GL_TEXTURE_3D                     0x806F
build.Lakka-RPi4.arm/toolchain/armv8a-libreelec-linux-gnueabi/sysroot/usr/include/GL/glcorearb.h:#define GL_TEXTURE_3D                     0x806F
build.Lakka-RPi4.arm/toolchain/armv8a-libreelec-linux-gnueabi/sysroot/usr/include/GLES2/gl2ext.h:#define GL_TEXTURE_3D_OES                 0x806F
build.Lakka-RPi4.arm/toolchain/armv8a-libreelec-linux-gnueabi/sysroot/usr/include/GLES2/gl2ext.h:#define GL_TEXTURE_3D                     0x806F
build.Lakka-RPi4.arm/toolchain/armv8a-libreelec-linux-gnueabi/sysroot/usr/include/GLES3/gl31.h:#define GL_TEXTURE_3D                     0x806F
build.Lakka-RPi4.arm/toolchain/armv8a-libreelec-linux-gnueabi/sysroot/usr/include/GLES3/gl32.h:#define GL_TEXTURE_3D                     0x806F
build.Lakka-RPi4.arm/toolchain/armv8a-libreelec-linux-gnueabi/sysroot/usr/include/GLES3/gl3.h:#define GL_TEXTURE_3D                     0x806F
build.Lakka-RPi.arm/toolchain/armv6zk-libreelec-linux-gnueabi/sysroot/usr/include/GLES2/gl2ext.h:#define GL_TEXTURE_3D_OES                                       0x806F
build.Lakka-S805.arm/toolchain/armv7a-libreelec-linux-gnueabi/sysroot/usr/include/GLES2/gl2ext.h:#define GL_TEXTURE_3D_OES                                       0x806F
build.Lakka-S8X2.arm/toolchain/armv7a-libreelec-linux-gnueabi/sysroot/usr/include/GLES2/gl2ext.h:#define GL_TEXTURE_3D_OES                                       0x806F
build.Lakka-S905.arm/toolchain/armv8a-libreelec-linux-gnueabi/sysroot/usr/include/GLES2/gl2ext.h:#define GL_TEXTURE_3D_OES                                       0x806F
build.Lakka-S912.arm/toolchain/armv8a-libreelec-linux-gnueabi/sysroot/usr/include/GLES2/gl2ext.h:#define GL_TEXTURE_3D_OES                                       0x806F
build.Lakka-Slice3.arm/toolchain/armv7ve-libreelec-linux-gnueabi/sysroot/usr/include/GLES2/gl2ext.h:#define GL_TEXTURE_3D_OES                                       0x806F
build.Lakka-Slice.arm/toolchain/armv6zk-libreelec-linux-gnueabi/sysroot/usr/include/GLES2/gl2ext.h:#define GL_TEXTURE_3D_OES                                       0x806F
build.Lakka-TinkerBoard.arm/toolchain/armv7ve-libreelec-linux-gnueabi/sysroot/usr/include/GLES2/gl2ext.h:#define GL_TEXTURE_3D_OES                 0x806F
build.Lakka-TinkerBoard.arm/toolchain/armv7ve-libreelec-linux-gnueabi/sysroot/usr/include/GLES2/gl2ext.h:#define GL_TEXTURE_3D                     0x806F
build.Lakka-TinkerBoard.arm/toolchain/armv7ve-libreelec-linux-gnueabi/sysroot/usr/include/GLES3/gl31.h:#define GL_TEXTURE_3D                     0x806F
build.Lakka-TinkerBoard.arm/toolchain/armv7ve-libreelec-linux-gnueabi/sysroot/usr/include/GLES3/gl32.h:#define GL_TEXTURE_3D                     0x806F
build.Lakka-TinkerBoard.arm/toolchain/armv7ve-libreelec-linux-gnueabi/sysroot/usr/include/GLES3/gl3.h:#define GL_TEXTURE_3D                     0x806F
build.Lakka-WeTek_Core.arm/toolchain/armv7a-libreelec-linux-gnueabi/sysroot/usr/include/GLES2/gl2ext.h:#define GL_TEXTURE_3D_OES                                       0x806F
build.Lakka-WeTek_Hub.arm/toolchain/armv8a-libreelec-linux-gnueabi/sysroot/usr/include/GLES2/gl2ext.h:#define GL_TEXTURE_3D_OES                                       0x806F
build.Lakka-WeTek_Play_2.arm/toolchain/armv8a-libreelec-linux-gnueabi/sysroot/usr/include/GLES2/gl2ext.h:#define GL_TEXTURE_3D_OES                                       0x806F
build.Lakka-WeTek_Play.arm/toolchain/armv7a-libreelec-linux-gnueabi/sysroot/usr/include/GLES2/gl2ext.h:#define GL_TEXTURE_3D_OES                                       0x806F
```

So only platform that does not have `GL_TEXTURE_3D_OES` is Generic, which uses OpenGL, not OpenGLES, hence `#if defined(HAVE_OPENGLES) || defined(HAVE_OPENGLES2)`...

Platforms, that have both, seem to support OpenGLES3. Platforms, that support only OpenGLES/2, do not have `GL_TEXTURE_3D`, only `GL_TEXTURE_3D_OES`.

But as I wrote - I am not a programmer, so I could be wrong here.

**Comment by natinusala** [comment]
That looks sane to me, especially if it's the same value.

**Pull request merged**
