### PR TITLE
Minor libretro update

### PR DESCRIPTION
**Pull request by natinusala**
This only fixes cores that have been rebased / broken since the last time the LE9 branch was updated. Fresh builds should work again !

### CODE REVIEW

**Comment by ToKe79** [comment]
Hi,
this PR (aba5a008b1c79afa9fdca267bff265352f098ff2) did not build correctly for any target - all (17) builds failed.
Logs can be found here: http://nightly.builds.lakka.tv/PRs/pr_860_000122/

_This is an automated message_

**Comment by natinusala** [comment]
@ToKe79 could you clean the sources folder and run the bot again for that PR please? I want to merge this one before #858

**Comment by ToKe79** [comment]
Sorry for waiting - cleaned and restarted.

**Comment by ToKe79** [comment]
Hi,
this PR (aba5a008b1c79afa9fdca267bff265352f098ff2) did not build correctly for all targets.
Following targets failed (1):
- Gamegirl.arm

Logs and images for testing can be found here: http://nightly.builds.lakka.tv/PRs/pr_860_000123/

_This is an automated message_

**Comment by natinusala** [comment]
I think this is good to go, can someone approve and merge this?

**Pull request merged**
