### PR TITLE
re-add additional RTL8xxx drivers + fix S905 wlan

### PR DESCRIPTION
**Pull request by ToKe79**

### CODE REVIEW

**Comment by ToKe79** [comment]
Hi,
this PR (65db1e5eae5d5bb7f8025f5b97c0a675ffc8d729) did not build correctly for all targets.
Following targets failed (1):
- RPi2.RPi4.arm

Logs and images for testing can be found here: http://nightly.builds.lakka.tv/PRs/pr_800_000092/

_This is an automated message_

**Comment by ToKe79** [comment]
Hi,
the build of this PR (6dc1358b925e8d629744edb0088a790c3b1010a9) finished successfully for all 46 targets.
Images for testing and logs are here: http://nightly.builds.lakka.tv/PRs/pr_800_000093/

_This is an automated message_

**Comment by ToKe79** [comment]
Just tested with my s905 box, wlan is working again :-)

**Comment by ToKe79** [comment]
Hi,
the build of this PR (3bbe675cc4316e80fe1be9f50cc866bc34fec894) finished successfully for all 46 targets.
Images for testing and logs are here: http://nightly.builds.lakka.tv/PRs/pr_800_000103/

_This is an automated message_

**Comment by natinusala** [comment]
Why did you remove `ADDITIONAL_DRIVERS` from the RPi targets? Aren't those drivers also used for USB Wi-Fi dongles?

**Comment by ToKe79** [comment]
added back also for RPi and RPi2 projects, except RPi4 board - they don't build, maybe not compatible with the newer kernel version?

**Comment by ToKe79** [comment]
Hi,
this PR (780acbc79caf3415252081e5b5f991fb7ce5dc3d) did not build correctly for all targets.
Following targets failed (45):
- Generic.x86_64
- Generic_VK_nvidia.x86_64
- RPi.arm
- RPi.GPICase.arm
- RPi2.arm
- RPi2.RPi4.arm
- Allwinner.Bananapi.arm
- Allwinner.Cubieboard2.arm
- Allwinner.Cubietruck.arm
- Allwinner.orangepi_2.arm
- Allwinner.orangepi_lite.arm
- Allwinner.orangepi_one.arm
- Allwinner.orangepi_pc.arm
- Allwinner.orangepi_plus.arm
- Allwinner.orangepi_plus2e.arm
- Allwinner.nanopi_m1_plus.arm
- imx6.cuboxi.arm
- imx6.udoo.arm
- OdroidC1.arm
- Odroid_C2.arm
- OdroidXU3.arm
- WeTek_Core.arm
- WeTek_Hub.arm
- WeTek_Play.arm
- WeTek_Play_2.arm
- Gamegirl.arm
- S8X2.S82.arm
- S8X2.M8.arm
- S8X2.T8.arm
- S8X2.MXIII-1G.arm
- S8X2.MXIII-PLUS.arm
- S8X2.X8H-PLUS.arm
- S805.MXQ.arm
- S805.HD18Q.arm
- S805.M201C.arm
- S805.M201D.arm
- S805.MK808B-Plus.arm
- S905.arm
- S912.arm
- Rockchip.TinkerBoard.arm
- Rockchip.ROCK64.arm
- Rockchip.ROC-RK3328-CC.arm
- Rockchip.MiQi.arm
- Rockchip.ROCKPro64.arm
- Rockchip.ROCK960.arm

Logs and images for testing can be found here: http://nightly.builds.lakka.tv/PRs/pr_800_000108/

_This is an automated message_

**Comment by ToKe79** [comment]
Hi,
the build of this PR (780acbc79caf3415252081e5b5f991fb7ce5dc3d) finished successfully for all 46 targets.
Images for testing and logs are here: http://nightly.builds.lakka.tv/PRs/pr_800_000108/

_This is an automated message_

**Pull request merged**
