### PR TITLE
Bump alsa-lib to the latest stable version

### PR DESCRIPTION
**Pull request by Ntemis**

### CODE REVIEW

**Comment by natinusala** [comment]
Images for testing can be found here http://nightly.builds.lakka.tv/PRs/pr_683_000012/

All platforms built, it's just a matter of testing if sound works

**Comment by gouchi** [comment]
- Tested on Generic x86_64 and Rockchip TinkerBoard : Both are ok.

**Comment by Ntemis** [comment]
Looks safe to merge. @natinusala  your call

**Comment by natinusala** [comment]
I will try it on RPi2 and ROCKPro64 tomorrow, but it should be fine seeing that Switch has it updated too

**Pull request merged**
