### PR TITLE
[WIP] Libretro update

### PR DESCRIPTION
**Pull request by kivutar**
I tested that everything compile properly. I had to fix 2 or 3 packages.

I've not yet tested the images for regressions.

I'll upload a batch.

### CODE REVIEW

**Comment by kivutar** [comment]
Builds are there http://static.kivutar.me/unstable/

**Comment by binaryhermit** [comment]
The controller mapping for a dualshock 3 controller on a Raspberry Pi 3B+ using the Raspberry Pi 2 build is very messed up....

**Comment by kivutar** [comment]
I'm getting black icons on RPi2, and no controller hotplug. Like if overlayfs was broken. Or config path changed.

**Comment by Ntemis** [comment]
I had the same issue a while back, i remember reporting it

**Comment by kivutar** [comment]
I found the cause of this. RetroArch is not reading /etc/retroarch.cfg anymore. So we need to find another way to set default values for Lakka.

**Pull request merged**
