### PR TITLE
New device: RK3399 - RK3328 rework - new RK3328 board: ROC-RK3328-CC

### PR DESCRIPTION
**Pull request by natinusala**
With the help of @Ntemis, I was able to port Lakka to the RK3399 SoC.

## Supported devices
* ROCKPro64
* Rock960 _(needs special on-board bootloader tweaking)_
* Odroid N1 _(untested)_

## Known issues
* Ethernet MAC address : the system uses a random MAC address. u-boot is supposed to read it from the efuses and pass it to Linux via command line
    * There is a patch available for Rockchip u-boot, it doesn't apply to ours, it will need porting
    * We use a hardcoded MAC address to avoid this issue ; this means that all Lakka installations on RK3399 boards will share the same MAC (don't use two of them on the same local network)
* ~~The HDMI resolution is wrong when booting the board with a cord already plugged in. Removing then putting back the cord once the board has booted fixes the issue until next reboot.~~
* If no ethernet cable is plugged in when booting, the `ethtool` service, needed to fix IPv6, adds a ten seconds delay (due to the "wait to be online" delay). This causes `systemd` to add a message when booting (`A start job is running for......` ). This taints the splash screen as the following logs are displayed.
    * The delay was reduced to 2s for convenience

## Untested features
* Jack audio
* Wi-Fi and Bluetooth (needs a [separate chip](https://www.pine64.org/?product=rockpro64-2x2-mimo-dual-band-wifi-802-11acbluetooth-4-1-module) which I own, it just needs testing)

## aarch64 libretro changes
The board now works in 32bit mode. Those changes are good to have as they add new cores, but are not necessary anymore.

* `desmume` works better than `desmume-2015` on some games (especially on OpenGL capable devices). As a result, I renamed the current core `desmume-2015` and added a new core, `desmume`
    * I added a patch to disable OGL in the core - this patch is reverted before building if the target device is OGL capable (this was the simplest solution as OGL is "hardcoded" into the makefile)
    * You may want to set `desmume-2015` as the new default core for the NDS playlist (current is `desmume`)
* Dolphin doesn't build on aarch64 at the moment. The issue has been forwarded to aliaspider, and I've removed it from aarch64 in the meantime.
* New core: `dosbox-svn`. This version of DOSBox contains an ARM64 dynarec, which improves the performances _a lot_ on such devices. It is also up to date with the standalone DOSBox SVN.
    * This core depends on SDL and SDL_net, which I've added to the system
* I added a new configuration (specific to the project) to `parallel-n64` to force GLES (ARM64 and GLES were previously an unknown configuration for the core)
* Some cores don't build on aarch64 and therefore were disabled on this architecture :
    * `dolphin`
    * `fuse-libretro`
    * `mesen`
    * `mupen64plus`
    * `picodrive`
    * `puae`
    * `redream`
    * `reicast`

## Build script changes

I added a new parameter to the build script, `BOARD`. This allows us to build RK3399 images like so :

* `PROJECT=Rockchip DEVICE=RK3399 BOARD=ROCKPro64 ARCH=arm make image`
* `PROJECT=Rockchip DEVICE=RK3399 BOARD=ROCK960 ARCH=arm make image`
* `PROJECT=Rockchip DEVICE=RK3399 BOARD=OdroidN1 ARCH=arm make image`

The build name will now take the board as a name if any, else the device if any, else the project (as before).

I also set `Lakka` as the default distribution, as there is no reason for it to be `LibreELEC` anymore.

## [SOLVED] Breaking changes to other Rockchip devices

In order to make it work, I had to make changes to Linux and u-boot for Rockchip, which some of them are breaking for other devices :

* **[SOLVED]** `linux` was updated (to the latest) - the new version uses a device-specific config instead of a project-specific config. As a result, each device should have its own Linux configuration, and the whole Rockchip configuration was removed. I added the new configurations for the other devices.
* **[SOLVED]** `u-boot` was updated to `2018.07` - some device-specific patches may be necessary to make them boot again.
* **[SOLVED]** `rkbin` was updated - this should not cause any issue but we never know (especially for RK3328 devices)
* **[SOLVED]** The way the images are created was changed (in `u-boot` `package.mk`). For some reason, the `DATAFILE` blob was truncated of one byte with a `dd ... skip=1`. This prevented the RK3399 from booting, so I removed this. I don't know what are the consequences of such a change on other Rockchip devices (chances are they will no longer boot - we can add a device-specific `skip` parameter if so).

**Everything boots properly.**

## Miscellaneous

* ~~I didn't add the project to the `build_all` script or Docker file.~~
* The `glmark2` package was fixed.
* `libdrm` was updated (from `2.4.81` to `2.4.93`).
* I added a new `systemd` patch necessary to build the system on Ubuntu 18.x.
* I removed `$CMDLINE` from the devices `mkimage` as it caused confusion with `$EXTRA_CMDLINE`
    * `$CMDLINE` was local to each device's `mkimage` so useless in the end
    * `$EXTRA_CMDLINE` is in each device's `options`
* I added a `rockchip-firmware` package to be on par with LibreELEC (necessary for Wi-Fi and Bluetooth)
    * Some associated `systemd` services were also added
* I removed the unused `mali` config entry in `modules-load.d`

### CODE REVIEW

**Comment by dmschwartzii** [comment]
Do you have a rock64 pro test image

**Comment by natinusala** [comment]
Sure, here it is : https://transfer.sh/vW3Sy/Lakka-Rockchip.ROCKPro64.arm-2.2-devel-20180921160305-r28232-g3191e6cf8.img.gz (link goes away in two weeks)

**Comment by dmschwartzii** [comment]
Any chance for Nanopi M4

**Comment by kivutar** [comment]
No regression on drm on other devices?

**Comment by natinusala** [comment]
Not that I'm aware of, however ROCK64 doesn't work anymore since the kernel update (RA crashes on launch) - I'm waiting for @Ntemis to report back with some logs

**Comment by ToKe79** [comment]
@natinusala @Ntemis I am getting this error:

`PROJECT=Rockchip DEVICE=RK3399 BOARD=OdroidN1 ARCH=arm make image -j8`

```
      BUILD    u-boot (target)
make[1]: Entering directory '/home/vudiq/projects/Lakka-LibreELEC/build.Lakka-OdroidN1.arm-2.2-devel/u-boot-2018.07'
  CLEAN   scripts/basic
  CLEAN   scripts/kconfig
make[1]: Leaving directory '/home/vudiq/projects/Lakka-LibreELEC/build.Lakka-OdroidN1.arm-2.2-devel/u-boot-2018.07'
make[1]: Entering directory '/home/vudiq/projects/Lakka-LibreELEC/build.Lakka-OdroidN1.arm-2.2-devel/u-boot-2018.07'
  HOSTCC  scripts/basic/fixdep
  HOSTCC  scripts/kconfig/conf.o
  YACC    scripts/kconfig/zconf.tab.c
  LEX     scripts/kconfig/zconf.lex.c
  HOSTCC  scripts/kconfig/zconf.tab.o
  HOSTLD  scripts/kconfig/conf
***
*** Can't find default configuration "arch/../configs/odroidn1_defconfig"!
***
make[2]: *** [scripts/kconfig/Makefile:128: odroidn1_defconfig] Error 1
make[1]: *** [Makefile:492: odroidn1_defconfig] Error 2
make[1]: Leaving directory '/home/vudiq/projects/Lakka-LibreELEC/build.Lakka-OdroidN1.arm-2.2-devel/u-boot-2018.07'
Makefile:29: recipe for target 'image' failed
make: *** [image] Error 1
```

**Comment by natinusala** [comment]
I have no idea what happened here but the Odroid N1 patch was reduced to a 0 bytes file : https://github.com/natinusala/Lakka-LibreELEC/tree/rk3399/projects/Rockchip/devices/RK3399/patches/u-boot/mainline

I will fix this ASAP

**Comment by ToKe79** [comment]
I still get the same error - maybe there is something hidden during the merge/rebase. Here are my steps - maybe I am doing something wrong?

```
$ git --version
git version 2.7.4
$ git remote -v
origin  git@github.com:ToKe79/Lakka-LibreELEC.git (fetch)
origin  git@github.com:ToKe79/Lakka-LibreELEC.git (push)
upstream        https://github.com/libretro/Lakka-LibreELEC (fetch)
upstream        https://github.com/libretro/Lakka-LibreELEC (push)
$ git status
On branch master
Your branch is up-to-date with 'upstream/master'.
nothing to commit, working directory clean
$ git fetch upstream pull/538/head:rk3399
remote: Enumerating objects: 42, done.
remote: Counting objects: 100% (42/42), done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 85 (delta 34), reused 40 (delta 32), pack-reused 43
Unpacking objects: 100% (85/85), done.
From https://github.com/libretro/Lakka-LibreELEC
 * [new ref]         refs/pull/538/head -> rk3399
$ git checkout rk3399
Switched to branch 'rk3399'
$ git rebase upstream/master
First, rewinding head to replay your work on top of it...
Applying: New device: RK3399
Using index info to reconstruct a base tree...
M       packages/libretro/core-info/package.mk
M       packages/libretro/fuse-libretro/package.mk
M       packages/libretro/mesen/package.mk
M       packages/libretro/reicast/package.mk
.git/rebase-apply/patch:208: trailing whitespace.
+
.git/rebase-apply/patch:217: trailing whitespace.
+
.git/rebase-apply/patch:288: trailing whitespace.
+
.git/rebase-apply/patch:297: trailing whitespace.
+
.git/rebase-apply/patch:321: trailing whitespace.

warning: squelched 1337 whitespace errors
warning: 1342 lines add whitespace errors.
Falling back to patching base and 3-way merge...
Removing projects/Rockchip/packages/u-boot/patches/u-boot-0001-tools-do-not-build-libfdt-Python-module.patch
Removing projects/Rockchip/linux/linux.arm.conf
Auto-merging projects/Rockchip/devices/RK3399/linux/linux.aarch64.conf
Auto-merging packages/libretro/reicast/package.mk
Auto-merging packages/libretro/mesen/package.mk
Auto-merging packages/libretro/fuse-libretro/package.mk
Applying: Rockchip: fix README
Applying: rk3399: add hardcoded eth mac address
Applying: build_all.sh: remove DISTRO=Lakka
Applying: build_all.sh: add rk3399 boards
Applying: Rockchip: fix Linux config for ROCK64, MiQi and Tinkerboard
Applying: Fixed rockchip-firmware package
Applying: Tinkerboard: remove obsolete patch
Applying: ROCK64: fix boot logs
Applying: MiQi & Tinkerboard: fix tty0
Applying: RK: update rkbin
Applying: ROCK64: remove obsolete Linux patch
Applying: rockchip-firmware: add more rules for rtl8723bs
Applying: RK: update Linux to 1a136976
Applying: RK: new RK3328 device, fixed linux version and config
Applying: RK: new RK3328 board: ROC-RK3328-CC
Applying: RK3399: fix 32bit image
Applying: RK: add ROC-RK3328-CC to the README
Applying: RK3328: remove aarch64 from the README
Applying: RK: updated linux and rkmpp
Applying: RK: added rockchip u-boot next to mainline u-boot (for roc-rk3328-cc)
Applying: RK: reduce ethtool delay from 10s to 2s
Applying: RK: restored odroid n1 patch
```
Then I try to build:
```
$ PROJECT=Rockchip DEVICE=RK3399 BOARD=OdroidN1 ARCH=arm make image -j8
./scripts/image mkimage

 =================================================================================
 Configuration for Lakka (community)
 =================================================================================

 Buildoptions:
 ======================================================
 - CPU (ARCH):                           cortex-a72.cortex-a53 (arm)
 - FLOAT:                                hard
 - FPU:                                  crypto-neon-fp-armv8
 - SIMD support:                         yes
 - LTO (Link Time Optimization) support: yes
 - GOLD (Google Linker) Support:         yes
 - LLVM support:

 Graphic configuration:
 ======================================================
 - OpenGL (GLX) support (provider):      no (no)
 - OpenGLES support (provider):          yes (mali-rockchip)
 - uvesafb support:                      no

 Hardware decoder configuration:
 ======================================================
 - Kodi Player driver:                   rkmpp
 - VAAPI Support:
 - VDPAU Support:

 Input device configuration:
 ======================================================
 - Remote support:                       no
 - ATV Remote support:                   no
 - CEC Adapter support:                  yes
 - Kodi Joystick support:                yes

 Misc. hardware configuration:
 ======================================================
 - ALSA support:                         yes
 - Pulseaudio support:                   no
 - Bluetooth support:                    yes
 - Include driver:                       rfkill
 - Include firmware:                     misc-firmware
 - Include firmware:                     wlan-firmware
 - Include firmware:                     rockchip-firmware

 Network service configuration:
 ======================================================
 - Avahi (Zeroconf) support:             yes
 - NFS mounting support:                 yes
 - SAMBA mounting support:               yes
 - SAMBA server support:                 yes
 - SFTP server support:                  yes
 - OpenVPN support:                      yes

 OS configuration:
 ======================================================
 - OEM Support:                          yes
 - Default ROOT Password:                root
 - Bootloader:                           u-boot
   - U-Boot configuration:               odroidn1_defconfig
   - U-Boot config file:
 - UDevil support:                       yes
 - Installer support:                    no

 Misc. Filesystems:
 ======================================================
 - Swap Support:                         no
 - exFAT Support (via Fuse):             yes
 - NTFS Support (via Fuse):              yes
 - Install HFS Tools:                    yes

 Kodi configuration:
 ======================================================
 - Kodi version:                         no
 - Kodi nonfree support:                 yes
 - Kodi Blu-Ray support:                 yes
   - Bluray BD+ support:                 yes
   - Bluray AACS support:                yes
 - Kodi DVDCSS support:                  yes
 - Kodi Airplay support:                 yes
 - Kodi Airtunes support:                yes
 - Kodi NFS support:                     yes
 - Kodi MySQL support:                   yes
 - Kodi Optical Drive support:           yes
 - Kodi SAMBA client support:            yes
 - Kodi SSH client support:              yes
 - Kodi UPNP support:                    yes
 - Kodi Webserver support:               yes
 - Include Skin:                         Confluence
 - Default Skin:                         Confluence
 - Include extra fonts:                  yes

 =================================================================================
 End Configuration for Lakka
 =================================================================================
[truncated]
  BUILD    linux (target)
make[1]: Entering directory '/home/vudiq/projects/Lakka-LibreELEC/build.Lakka-OdroidN1.arm-2.2-devel/linux-aa8bacf821e5c8ae6dd8cae8d64011c741659945'
scripts/kconfig/conf  --oldconfig Kconfig
#
# configuration written to .config
#
make[1]: Leaving directory '/home/vudiq/projects/Lakka-LibreELEC/build.Lakka-OdroidN1.arm-2.2-devel/linux-aa8bacf821e5c8ae6dd8cae8d64011c741659945'
      CLEAN    u-boot
          * Removing /home/vudiq/projects/Lakka-LibreELEC/build.Lakka-OdroidN1.arm-2.2-devel/u-boot-2018.07 ...
      UNPACK   u-boot
          APPLY PATCH (common - mainline)   projects/Rockchip/packages/u-boot/patches/mainline/u-boot-0001-fix-libfdt-python-includes-path.patch
patching file scripts/dtc/pylibfdt/Makefile
          APPLY PATCH (common - mainline)   projects/Rockchip/packages/u-boot/patches/mainline/u-boot-0002-rockchip-miqi-enable-led-gpio&keyboard.patch
patching file configs/miqi-rk3288_defconfig
Hunk #1 succeeded at 47 with fuzz 1 (offset 4 lines).
Hunk #2 succeeded at 60 (offset 4 lines).
Hunk #3 succeeded at 73 with fuzz 2 (offset 2 lines).
          APPLY PATCH (common - mainline)   projects/Rockchip/packages/u-boot/patches/mainline/u-boot-0003-rockchip-tinker-enable-rockchip-video-driver.patch
patching file configs/tinker-rk3288_defconfig
Hunk #1 succeeded at 81 (offset 3 lines).
          APPLY PATCH (common - mainline)   projects/Rockchip/packages/u-boot/patches/mainline/u-boot-0004-mac-address-env.patch
patching file board/rockchip/evb_rk3399/evb-rk3399.c
      BUILD    u-boot (target)
make[1]: Entering directory '/home/vudiq/projects/Lakka-LibreELEC/build.Lakka-OdroidN1.arm-2.2-devel/u-boot-2018.07'
make[1]: Leaving directory '/home/vudiq/projects/Lakka-LibreELEC/build.Lakka-OdroidN1.arm-2.2-devel/u-boot-2018.07'
make[1]: Entering directory '/home/vudiq/projects/Lakka-LibreELEC/build.Lakka-OdroidN1.arm-2.2-devel/u-boot-2018.07'
  HOSTCC  scripts/basic/fixdep
  HOSTCC  scripts/kconfig/conf.o
  YACC    scripts/kconfig/zconf.tab.c
  LEX     scripts/kconfig/zconf.lex.c
  HOSTCC  scripts/kconfig/zconf.tab.o
  HOSTLD  scripts/kconfig/conf
***
*** Can't find default configuration "arch/../configs/odroidn1_defconfig"!
***
make[2]: *** [scripts/kconfig/Makefile:128: odroidn1_defconfig] Error 1
make[1]: *** [Makefile:492: odroidn1_defconfig] Error 2
make[1]: Leaving directory '/home/vudiq/projects/Lakka-LibreELEC/build.Lakka-OdroidN1.arm-2.2-devel/u-boot-2018.07'
Makefile:29: recipe for target 'image' failed
make: *** [image] Error 1
```
But the patch is there:
```
$ file projects/Rockchip/devices/RK3399/patches/u-boot/mainline/u-boot-0002-board-add-support-for-odroid-n1.patch
projects/Rockchip/devices/RK3399/patches/u-boot/mainline/u-boot-0002-board-add-support-for-odroid-n1.patch: unified diff output, ASCII text
$ cat projects/Rockchip/devices/RK3399/patches/u-boot/mainline/u-boot-0002-board-add-support-for-odroid-n1.patch | wc -l
1069
```

**Comment by natinusala** [comment]
Can you try to move the patches from 
`projects/Rockchip/devices/RK3399/patches/u-boot/mainline/`
to 
`projects/Rockchip/devices/RK3399/patches/u-boot/`

Basically remove the mainline folder ?

**Comment by ToKe79** [comment]
I guess the patches are not picked up, because in this case `PKG_DIR = /home/vudiq/projects/Lakka-LibreELEC/projects/Rockchip/packages/u-boot` so it does not look in `projects/Rockchip/devices/...` for patches.
We would have to modify the `for` loop to look also in `$PROJECTS_DIR/$PROJECT/devices/$DEVICE/$PKG_NAME/patches/$patch_dir/*.patch`.

**Comment by ToKe79** [comment]
now it fails with:
```
$ PROJECT=Rockchip DEVICE=RK3399 BOARD=OdroidN1 ARCH=arm make image -j8
./scripts/image mkimage                  
 
 =================================================================================
 Configuration for Lakka (community)     
 =================================================================================
 
 Buildoptions:
 ======================================================
 - CPU (ARCH):                           cortex-a72.cortex-a53 (arm)
 - FLOAT:                                hard
 - FPU:                                  crypto-neon-fp-armv8                                                                                                         
 - SIMD support:                         yes
 - LTO (Link Time Optimization) support: yes                                                                                                                          
 - GOLD (Google Linker) Support:         yes                                                                                                                          
 - LLVM support:
[truncated]
      INSTALL    tz (target)             
  INSTALL    gcc (target)
  BUILD    linux (target)                
make[1]: Entering directory '/home/vudiq/projects/Lakka-LibreELEC/build.Lakka-OdroidN1.arm-2.2-devel/linux-aa8bacf821e5c8ae6dd8cae8d64011c741659945'
scripts/kconfig/conf  --oldconfig Kconfig
#                                                                                                                                                                     
# configuration written to .config
#                                                                                                                                                                     
make[1]: Leaving directory '/home/vudiq/projects/Lakka-LibreELEC/build.Lakka-OdroidN1.arm-2.2-devel/linux-aa8bacf821e5c8ae6dd8cae8d64011c741659945'
make[1]: Entering directory '/home/vudiq/projects/Lakka-LibreELEC/build.Lakka-OdroidN1.arm-2.2-devel/linux-aa8bacf821e5c8ae6dd8cae8d64011c741659945'
scripts/kconfig/conf  --silentoldconfig Kconfig
  CHK     include/config/kernel.release  
  CHK     include/generated/uapi/linux/version.h
[truncated]
  INSTALL sound/usb/snd-usbmidi-lib.ko                                                                                                                                
  INSTALL /home/vudiq/projects/Lakka-LibreELEC/build.Lakka-OdroidN1.arm-2.2-devel/linux-aa8bacf821e5c8ae6dd8cae8d64011c741659945/.install_pkg/usr/lib/firmware/av7110/bootcode.bin
  INSTALL /home/vudiq/projects/Lakka-LibreELEC/build.Lakka-OdroidN1.arm-2.2-devel/linux-aa8bacf821e5c8ae6dd8cae8d64011c741659945/.install_pkg/usr/lib/firmware/ttusb-budget/dspbootcode.bin
  DEPMOD  4.4.154
make[1]: Leaving directory '/home/vudiq/projects/Lakka-LibreELEC/build.Lakka-OdroidN1.arm-2.2-devel/linux-aa8bacf821e5c8ae6dd8cae8d64011c741659945'
      INSTALL    initramfs (target)
          INSTALL    libc (init)
              INSTALL    glibc (init)
          INSTALL    busybox (init)
          INSTALL    linux (init)
          INSTALL    plymouth-lite (init)
              INSTALL    gcc (init)
              INSTALL    libpng (target)
                  INSTALL    zlib (target)
          INSTALL    util-linux (init)
          INSTALL    e2fsprogs (init)
          INSTALL    dosfstools (init)
              INSTALL    dosfstools (target)
          INSTALL    open-iscsi (init)
              INSTALL    util-linux (target)
.
./sbin
./dev
./dev/console
./functions
./init
./etc
[truncated]
./lib     
./splash  
./splash/splash-720.png
./splash/splash-1200.png 
./splash/splash-768.png
./splash/splash-1080.png 
./splash/splash-2160.png
./bin
7357 blocks
make[1]: Entering directory '/home/vudiq/projects/Lakka-LibreELEC/build.Lakka-OdroidN1.arm-2.2-devel/linux-aa8bacf821e5c8ae6dd8cae8d64011c741659945'
  CHK     include/config/kernel.release
  CHK     include/generated/uapi/linux/version.h
  CHK     include/generated/utsrelease.h
  CHK     scripts/mod/devicetable-offsets.h
make[2]: *** No rule to make target 'arch/arm64/boot/dts/rockchip/rk3399-odroidn1-linux.dtb'.  Stop.
make[1]: *** [arch/arm64/Makefile:122: rockchip/rk3399-odroidn1-linux.dtb] Error 2
make[1]: Leaving directory '/home/vudiq/projects/Lakka-LibreELEC/build.Lakka-OdroidN1.arm-2.2-devel/linux-aa8bacf821e5c8ae6dd8cae8d64011c741659945'
Makefile:29: recipe for target 'image' failed
make: *** [image] Error 2
```

**Comment by ToKe79** [comment]
All images built. I had to update `citra` and `sameboy` packages, otherwise no errors encountered.
http://nightly.builds.lakka.tv/special_builds/rk3399/

**Comment by caoshenwen** [comment]
Thank you very much!

**Pull request merged**
