### PR TITLE
libretro: update to latest core and latest RetroArch stable

### PR DESCRIPTION
**Pull request by gouchi**
Update core to latest and RetroArch to latest stable.

Most important changes : 

- easyrpg : add libfmt to package dependencies
- gcc :  add libatomic for kronos core
- liblcf : update needed for easyrpg and remove benchmark (not needed) as it failed
- opera: rename 4do core
- play! : remove std++ static build
- retroarch : update to version 1.8.8

### CODE REVIEW

**Comment by ToKe79** [comment]
Hi,
this PR (89086f321b4450a85ec48733045acc964c28c239) did not build correctly for any target - all (16) builds failed.
Logs can be found here: http://nightly.builds.lakka.tv/PRs/pr_958_000146/

_This is an automated message_

**Comment by natinusala** [comment]
Should we take this opportunity to add gomp support to our toolchain? I know bsnes uses it, and I think flycast needs it now as well?

**Comment by gouchi** [comment]
Why not if it is not breaking the build too much ;-)

**Comment by Ghabry** [comment]
The current latest release of EasyRPG Player is 0.6.2.1 (96fdac3). See the tags.
Also doesn't depend on fmtlib yet, but is good to have this already in - The next release will need it ;)

**Comment by ToKe79** [comment]
Hi,
this PR (647cbb9f033ad317ce374f19fca21457a7452394) did not build correctly for any target - all (16) builds failed.
Logs can be found here: http://nightly.builds.lakka.tv/PRs/pr_958_000153/

_This is an automated message_

**Pull request merged**
